### ISSUE TITLE
spin2cpp.c - array index out of bounds error

### ISSUE THREAD

**Issue by calabroa** [totalspectrum/spin2cpp#1]
As compiled on os x:

spin2cpp.c:717:13: error: array index 3 is past the end of the array (which contains 3 elements) [-Werror,-Warray-bounds]
            optchar[3] = 0;
            ^       ~
spin2cpp.c:713:13: note: array 'optchar' declared here
            char optchar[3];
            ^
1 error generated.

**Comment by totalspectrum** [comment]
Thanks! I've modified the  Makefile a bit to put build outputs inside a build directory; hopefully that will make the OSX build a little cleaner (it certainly makes cross-compilation easier).

**Comment by Wuerfel21** [comment]
sorry, did not mean to reference this issue
