### ISSUE TITLE
For/Next loop rolls over

### ISSUE THREAD

**Issue by aaaaaaaargh** [totalspectrum/spin2cpp#101]
Hello,
in Basic the following loop should exit but instead it runs forever (same for other data types)
```
dim a as ubyte
for a = 0 to 255
   print a 
next
```
Tested on propeller 1 only

**Comment by totalspectrum** [comment]
I don't think this is a bug. Since a is a ubyte, it is never outside the range 0..255, so the condition in the for loop will never be false.

FreeBASIC on Linux has the same behavior (tested with version 1.05.0),

**Comment by totalspectrum** [comment]
I have added a warning for some cases like this.

**Comment by aaaaaaaargh** [comment]
Sorry, but I have to disagree, imho a for..next loop by definition shouldn't loop forever.
And just because Freebasic does the same thing doesn't mean its not wrong. 
Futhermore the following Basics don't loop forever in this situation:
Basic Stamp  (while we're on the subject of parallax)
PicAxe
PureBasic 
PowerBasic
Bascom AVR
Great Cow Basic
I'm sure I'll find more examples ;-)

**Comment by drawkula** [comment]
```
#include <stdio.h>
#include <stdint.h>

void main() {
  uint8_t i;

  for( i=0 ; i<=255 ; i++ )
    putchar( 'A' + (i & 15) );

  putchar(10);
}
```
This loops with GCC and FlexCC and it would confuse me if this being translated to BASIC would behave differently.

**Comment by Wuerfel21** [comment]
Well, C's for loop has different, more well-defined semantics and behavior, so I don't think it's relevant. BASIC's FOR could be implemented a bunch of different ways that differ in this edge case. I don't think it is unreasonable to expect `for a = 0 to 255` to not loop forever and I do think there's many cases where one'd want to do that. However, this would need to be consistent with the behavior of non-constant loop ranges, which would probably result in worse code for these cases. There isn't really a reason to make the loop index 8 bit to begin with though, so why do we even have this discussion?
