### ISSUE TITLE
Doesn't compile anymore, bison syntax error

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#103]
Used to work, now just does this (likely related to #95 ?)

```
D:\Projektkram\spin2cpp>make
bison -t -b ./build/spin -d frontends/spin/spin.y
frontends/spin/spin.y:7.20-27: Syntaxfehler, unerwartetes {...}
make: *** [Makefile:86: build/spin.tab.h] Error 1
```
(Since some idiot decided it'd be a good idea to localize bison's error messages, I'll tell you that `Syntaxfehler, unerwartetes {...}` means `Syntax error, unexpected {...}`)

**Comment by totalspectrum** [comment]
Which version of bison are you using? Any 3.x bison should recognize that syntax.

**Comment by Wuerfel21** [comment]
Oh, I'm on 2.4.1, that's probably a bit old. I guess it's time to go find a newer version...

**Comment by Wuerfel21** [comment]
Yep, that fixed it.
However, do note that the first search result for "bison windows" is 2.4.1 with a nice installer and the second result is 3.7.1, but there is no installer and the binary is `win_bison` so you have to manually rename it. Urgh. Better put some kind of instructions on this somewhere.

**Comment by totalspectrum** [comment]
I've re-written the Makefile and yacc files so you can do "make YACCVER=bison2" to run with bison 2 (I think). GNU has really messed up bison compatibility between 2.4, 3.4 (the one I was using) and 3.7, and trying to write code that works with all of these is a pain. Not sure I've succeeded, but it's partly working at least.

**Comment by Wuerfel21** [comment]
Cool, will give it a try tomorrow. Then this can probably be closed.

**Comment by Wuerfel21** [comment]
nope, doesn't work, gives me this fun error instead (regardless of what I pass as YACCVER and which `bison` is on PATH)
```
D:\Projektkram\spin2cpp>make YACCVER=bison2
yacc -p spinyy -t -b ./build/spin -d frontends/spin/spin.y
/c/program files/gnuwin32/bin/yacc: line 2: c:/progra~1/bison/bin/bison: No such file or directory
make: *** [Makefile:148: build/spin.tab.h] Error 127
```
8.3 file names? lol.

Anyways, assuming `yacc` is aliased to `bison` seems to be a bad idea

**Comment by totalspectrum** [comment]
That error message is not my Makefile's fault, it sounds like the bison installation put a bad yacc shell script in. Could you try just "make YACC=bison"? That should set YACCVER automatically based on the bison version.

**Comment by Wuerfel21** [comment]
> That error message is not my Makefile's fault, it sounds like the bison installation put a bad yacc shell script in.
Yeah that's the point. The bison 2.4.1 I got came with a broken shell script, the 3.7.1 came with no `yacc` at all.

**Comment by Wuerfel21** [comment]
Adding `YACC=bison` makes it work though, so I guess all is well, there just needs to be documentation about this kerfuffle

**Comment by totalspectrum** [comment]
YACC=bison is the default now so I think this should all work again. I wish GNU hadn't changed bison 3.7, we had code that worked with 2.x and 3.0 but it broke when 3.7 arrived and I had to re-write it :(.
