### ISSUE TITLE
Parameters to empty function are not eliminated

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#104]
```spin
PUB main
  test1(string("Oh no!!!!"))
  outa:=test2
  outa:=test2
PUB test1(str)
   ' empty
PUB test2
  ' nonsense function
  repeat inb
    result <<=1
    result |= ina
```
The "Oh no!!!!" string is not eliminated and is even still moved into `arg01`

**Comment by totalspectrum** [comment]
In general the parameters cannot be eliminated because they may have side effects. It would be nice to eliminate the ones we can, but quite a bit of work. So I'm going to close this as a "won't fix".
