### ISSUE TITLE
Missing error/warning when taking address of RES'd symbol

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#105]
```spin
PUB main
outa := @example
DAT
org
origin        nop
example       res 1
```
PropTool and openspin both error out on this example

**Comment by Wuerfel21** [comment]
Relatedly, this should also warn/err:
```spin
PUB main
example := ina
DAT
org
origin        nop
example       res 1
```

**Comment by totalspectrum** [comment]
bstc doesn't seem to be upset by the first example, and perhaps there's some case where it might be useful to take the hub address of the RES memory, so I've made that a warning. The second example produces a related warning and then an error.

Thanks for the bug report!
