### ISSUE TITLE
insert$ cuts off last character

### ISSUE THREAD

**Issue by aaaaaaaargh** [totalspectrum/spin2cpp#106]
The insert$ function in BASIC cuts off the last character:
Source:
```
Print Insert$("1234","Howdy",0)
Print Insert$("1234","Howdy",1)
Print Insert$("1234","Howdy",10)
Print Insert$("1234","Howdy",2)
```
Output:
```
Howdy1234    OK
Howdy1234    OK  
1234Howdy    OK
1Howdy23     Aargh Last Character is missing

```

bug is Line 139 in stringlibp2.bas
rightChunk$ = mid$(base$, offset, len(base$) - offset)
should be
rightChunk$ = mid$(base$, offset, len(base$) - offset +1)

**Comment by totalspectrum** [comment]
Thanks for the bug report. This is fixed in the github source code now (will be in 5.0.6)
