### ISSUE TITLE
Redefining local vars as functions doesn't produce an error

### ISSUE THREAD

**Issue by avsa242** [totalspectrum/spin2cpp#107]
Hi Eric,

Should the compiler reject this? Not sure if I stumbled on a feature I'm misusing, but I accidentally did something like this in a spin2 program (P2), and once I figured out this is what was causing the very strange behavior, created this distilled test to confirm:

```
PUB Main() | aa, bb

    'aa()    ' makes no difference - uncommented or not
    'bb()    '

PUB aa() | a ' redefine aa as a method/function: OK (PUB/PRI no diff.)

    a := 1   ' makes no difference

PUB bb() | b ' ditto

    b := 2
```

What _does_ fail, is if the variables were declared in a VAR block.

Thanks!

**Comment by totalspectrum** [comment]
That's certainly the way C works -- local variables have local scope, and have no effect on anything outside of the function they're declared in. And I think most languages/compilers follow that rule. Does Chip's Spin2 work differently?

**Comment by avsa242** [comment]
![PNut-035f-err-unique-var-name](https://user-images.githubusercontent.com/10009016/106453457-5d965e00-6457-11eb-8ee6-4b1a3b9324cb.png)

Ahhh I didn't think of that...that's true, but yes, I just tried the latest PNut and it complains about the variable. Maybe not the _best_ example, but OpenSpin complains about the spin1 equivalent code, too.

**Comment by totalspectrum** [comment]
Ugh. I don't think I'm going to deal with this mess. I guess in theory I could add another pass over the code and throw an error if any local variables shadow methods, but frankly I'm not sure that's a feature rather than a bug.
I will add a note to the documentation about this though. Thanks for bringing it up!
