### ISSUE TITLE
Add option to use 16 bit pointers on P1

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#108]

**Comment by totalspectrum** [comment]
Using 16 bit pointers (and perhaps even 16 bit integers) would definitely save space. Unfortunately this would cause trouble with the garbage collector, which uses some of the otherwise unused upper bits to distinguish pointers from random data.

**Comment by Wuerfel21** [comment]
That seems like a fair tradeoff, especially if one's not using the GC or any dynamic memory at all.
