### ISSUE TITLE
Matched case # affects generated code, even if code in both cases is identical

### ISSUE THREAD

**Issue by avsa242** [totalspectrum/spin2cpp#109]
Hi Eric,

In the attached, code, if I modify the _mode var in Main(), I get different generated code from the inner-most loops (a faster `rep`-based loop vs a slower `djnz`-based loop) for the two cases in `TestCase()`, despite their identical code. If I swap the case constants (0, 2 <-> 1, 3) as commented, the disparity moves, i.e., case 1, 3 now becomes the faster case.
Both generate equal code if an '`other:`' case is added.

Is it expected the compiler will behave this way? It's an easy fix...just make sure to add an other: case, but I just thought significant timing differences like this might catch others out, too if they're not aware of it.

This is with flexspin latest git, as of about 30min ago.
Also note this wiggles pins 0..2, mostly pin 1 ...helps to have an LA attached to see the difference.

Thanks!
Jesse

[case_matched-case-affects-generated-loop-type.spin2.zip](https://github.com/totalspectrum/spin2cpp/files/5976356/case_matched-case-affects-generated-loop-type.spin2.zip)

**Comment by totalspectrum** [comment]
I think this should be fixed now, or at least better. The code was failing to optimize loops when they were the last thing in the function.
Thanks for the bug report!

**Comment by avsa242** [comment]
Confirmed, thanks!
