### ISSUE TITLE
spin2cpp --asm error "CogInit target must be in hub memory" on Propeller BOE ADCTest code

### ISSUE THREAD

**Issue by dgately** [totalspectrum/spin2cpp#11]
This project (ADCTest for Propeller BOE downloaded from Parallax) fails to build as PASM, but builds fine for C & C++.

With the --asm option of spin2cppm this fails on the line: "success := cog := (cognew(AdcLoop(chlist), @stack) + 1)" inside the file "PropBOE ADC.spin" which is an object used by the ADCTest.spin file (see the attached ADCTest.zip file for all project files).

Unzip the following and open ADCTest.spin with spinconvert.tcl, set Options to "Pasm Output":
[ADCTest.zip](https://github.com/totalspectrum/spin2cpp/files/190338/ADCTest.zip)

Result:
```
spin2cpp --noheader -g --asm --code=cog --data=hub -o ADCTest.pasm ADCTest.spin
PropBOE ADC.spin:86: error: Coginit target must be in hub memory
child process exited abnormally
```

**Comment by totalspectrum** [comment]
I don't think this one is a bug: the coginit instruction really does need its target to be in hub memory, so in practice coginit is only going to be supported if --code=hub is given. I'll change the error message to try to make this clearer.

Thanks,
Eric
