### ISSUE TITLE
QSIN causes error in Spin1 for P2

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#111]
```spin
Pub main
OUTA := qsin(1,2,3)
```
causes...
```
$ flexspin -2b flexspin_bug.spin
Propeller Spin/PASM Compiler 'FlexSpin' (c) 2011-2021 Total Spectrum Software Inc.
Version 5.1.1 Compiled on: Feb 21 2021
flexspin_bug.spin
_gc_:366: error: Unknown symbol _
_gc_:367: error: Unknown symbol length
```

**Comment by totalspectrum** [comment]
Aargh. It's worse than that, not only was there a copy-paste error it also implemented qsin and qcos incorrectly for negative values. That's what I get for trying to squeeze a new feature in at the last minute and not testing it properly :(. Thanks for the bug report, it's fixed in github now.
