### ISSUE TITLE
Segmentation fault when using nonexistant constant as start of a REPEAT FROM TO with negative end

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#112]
```spin
PUB main
repeat i from DOES_NOT_EXIST to -1
```
This is oddly specific.

**Comment by Wuerfel21** [comment]
Infact, it also happens when the symbol is defined as a variable
```spin
VAR
long DOES_NOT_EXIST
PUB main
repeat i from DOES_NOT_EXIST to -1
```

**Comment by totalspectrum** [comment]
Thanks, "-1" is parsed as "-" "1" and it was messing up on handling the loop termination clause when the "-" operator was there. It's fixed in github now.
