### ISSUE TITLE
Bug with SEND in Spin2

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#113]
```spin
CON
_CLKFREQ = 150_000_000
OBJ
pst : "jm_fullduplexserial.spin2"
PUB main()
pst.start(pst.RX1,pst.TX1,0,115_200)
send:=@pst.tx
notmain()
PRI notmain()
repeat
  send(strsend(string(" ABCD")))
  waitms(1000)
PRI strsend(str) | c
repeat while c:=byte[str++]
  send(c)
```
PropTool 2.5.1 prints "ABCD" as expected, flexspin prints "ABCDD"

**Comment by totalspectrum** [comment]
Something very strange is going on here -- this only happens with "jm_fullduplexserial", not with "jm_serial" or "SmartSerial". I wonder if it might actually be a timing bug in jm_fullduplexserial?

**Comment by totalspectrum** [comment]
Oh, interesting -- the problem goes away if I just do send(" ABCD") instead of send(strsend(string(" ABCD"))). That makes it more likely to be a flexspin bug. I'll try to investigate some more.

**Comment by totalspectrum** [comment]
Ah, I see now -- if there's a single argument to SEND the compiler skipped checkiing the details, which is wrong if the argument is a function call and returns no values. I've checked a fix in to github. Thanks for the bug report!
