### ISSUE TITLE
VSCode error parse: filenames in errors inconsistent (relative/absolute)

### ISSUE THREAD

**Issue by ironsheep** [totalspectrum/spin2cpp#115]
VSCode expects filenames in error messages to **all be relative** or **all be absolute** paths to the files.

At the moment (v5.1.1) the messages are inconsistent (shown below) and are breaking the error parsing in VSCode.
It generates an error saying it can't find the file associated with the form it's not expecting.

Flexspin v5.1.1 is generating the following:

For included file:
```
Version 5.1.1 Compiled on: Feb 21 2021
jm_p2-es_matrix_control_demo.spin2
|-jm_prng.spin2
|-jm_p2-es_matrix.spin2
|-jm_p2-es_control.spin2
|-jm_serial.spin2
|-|-jm_nstr.spin2
/Users/stephen/Dropbox/PropV2-Shared/Projects/VSCode-TESTs/Proj-LEDs/jm_p2-es_matrix_control_demo/jm_p2-es_control.spin2:89: error: Unknown symbol bits
```

For top-level file:
```
Version 5.1.1 Compiled on: Feb 21 2021
jm_p2-es_matrix_control_demo.spin2
|-jm_prng.spin2
|-jm_p2-es_matrix.spin2
|-jm_p2-es_control.spin2
|-jm_serial.spin2
|-|-jm_nstr.spin2
jm_p2-es_matrix_control_demo.spin2:157: error: Unknown symbol mode
```

That is it's generating both forms Absolute for included files and Relative for the top level.
This needs to be one or the other, not both forms.

I suggest using a relative path to the folder containing the top-level file for all error messages.

Technically, as long as all error messages are in one form(absolute -or- relative) we can make this work under VSCode.

**Comment by totalspectrum** [comment]
Huh, that sounds like a bug in VSCode -- why doesn't it just use the file name as presented, rather than worrying about whether it's relative or absolute?
Trying to calculate relative paths would be very hard, because objects may come from any path, for example:
obj
  ser: "/opt/myobjects/serial.spin"
If that's included in a file /home/user/toplevel.spin, we'd have to walk all the way up to root in order to make a relative path :(.
I can add an option that'll force all paths to be printed as absolute.

**Comment by ironsheep** [comment]
It's a documented feature?!  ;-)   See  [Defining a Problem Matcher](https://code.visualstudio.com/docs/editor/tasks#_defining-a-problem-matcher)

And, fundamentally, I agree with you, but I also see how they could get there.

In the end, I reread that section and I had missed an autoDetect setting.  I converted to using that and now all forms of your error reporting work as desired.  

So, Ignore this Issue!  I'm posting this comment but I'll let you close this issue after you've read this response.

**Comment by totalspectrum** [comment]
Too late, I've added the -Wabs-paths option to the github source code already :). But if you've found a better solution then great. I'll leave -Wabs-paths in there in case some other IDE needs it.
