### ISSUE TITLE
Please add option to NOT stop on first error

### ISSUE THREAD

**Issue by ironsheep** [totalspectrum/spin2cpp#116]
In VSCode we are used to seeing all errors present and fixing them.

The behavior I'm seeing is that the compiler stops when it encounters any error.

This is both less informative as we don't know how many errors are really present and it takes longer to resolve a number of errors as we must iterate thru them all one by one.

I'm not finding an option to cause this behavior in Flexspin v5.1.1.

```
stephen@ev3 jm_p2-es_matrix_control_demo [] $ flexspin.mac -h
Propeller Spin/PASM Compiler 'FlexSpin' (c) 2011-2021 Total Spectrum Software Inc.
Version 5.1.1 Compiled on: Feb 21 2021
usage: flexspin.mac [options] filename.spin | filename.bas
  [ -h ]              display this help
  [ -L or -I <path> ] add a directory to the include path
  [ -o <name> ]      set output filename to <name>
  [ -b ]             output binary file format
  [ -e ]             output eeprom file format
  [ -c ]             output only DAT sections
  [ -l ]             output DAT as a listing file
  [ -f ]             output list of file names
  [ -g ]             enable debug statements
  [ -q ]             quiet mode (suppress banner and non-error text)
  [ -p ]             disable the preprocessor
  [ -D <define> ]    add a define
  [ -u ]             ignore for openspin compatibility (unused method elimination always enabled)
  [ -2 ]             compile for Prop2
  [ -O# ]            set optimization level:
          -O0 = no optimization
          -O1 = basic optimization
          -O2 = all optimization
  [ -H nnnn ]        set starting hub address
  [ -E ]             skip initial coginit code (usually used with -H)
  [ -w ]             compile for COG with Spin wrappers
  [ -Wall ]          enable warnings for language extensions and other features
  [ -Werror ]        make warnings into errors
  [ -C ]             enable case sensitive mode
  [ -x ]             capture program exit code (for testing)
  [ --code=cog ]     compile for COG mode instead of LMM
  [ --fcache=N ]     set FCACHE size to N (0 to disable)
  [ --fixedreal ]    use 16.16 fixed point in place of floats
  [ --lmm=xxx ]      use alternate LMM implementation for P1
           xxx = orig uses original flexspin LMM
           xxx = slow uses traditional (slow) LMM
  [ --version ]      just show compiler version
stephen@ev3 jm_p2-es_matrix_control_demo [] $ 
```

Please add an option to not stop compiling on the first error.

If I've missing finding an option already present please let me know this as well.

**Comment by totalspectrum** [comment]
Actually it's always continued and produced as many errors as required *within any given pass*, but stops at the end of the pass if there are errors. There are many passes internally and so you'd often only see a subset of errors.
I've added a new option -Wmax-errors=N to keep running passes as long as the total number of errors is less than N. Probably you'll want to use something like -Wmax-errors=99 from VSCode.
Thanks for the suggestion!

**Comment by ironsheep** [comment]
Thanks for the change. That should work just fine. 

Please let me know when a version containing this is avail. for testing.

**Comment by totalspectrum** [comment]
The source is checked in to github so if you can build it yourself then it's available. There's also a beta version of the binary on my patreon page. I hope to have a final public release later this weekend.
