### ISSUE TITLE
Spin2 word operators parse as instructions in DAT blocks

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#118]
Two examples, but I assume all operators that share a name with an instruction are affected.
```
DAT
long 5 sar 1
long decod 31
```

(Why are these a thing, anyways? The Spin1 style operators are so much nicer...(except for those stupid compares))

**Comment by totalspectrum** [comment]
Ah, I forgot that would be a problem with Spin2's operators (and yes, I agree that the Spin1 style operators are nicer!)

I've added some code to stop looking for instructions once one has been seen on a line (or once a data declaration like LONG is spotted). I think this fixes this problem.
