### ISSUE TITLE
Host filesytem: fread after fgetc reads garbage

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#124]
Time for your daily dose of bug report....
```c
#include <stdio.h>
void main() {  
  printf("Startup!\n");
  mount("/fs",_vfs_open_host());  
  FILE *jfile = fopen("/fs/bughello.dat","r");
  for(;;) {
    char c = fgetc(jfile);
    //fread(&c,1,1,jfile);
    if (c) putc(c,stdout);
    else break;
  }
  unsigned int i;
  fread(&i,1,4,jfile);
  printf("\n%08X\n",i);
}
```
Replacing the `fgetc` with the commented out `fread` code reads the correct data (`04030201`)

Here's the `bughello.dat`,
[bughello.zip](https://github.com/totalspectrum/spin2cpp/files/6416682/bughello.zip)
 which was created by punching this into `irb`:
```rb
File.binwrite "bughello.dat","Hello World!\0\x01\x02\x03\x04".b
```

**Comment by totalspectrum** [comment]
Thanks. This should be fixed in github now.
