### ISSUE TITLE
Incorrect variable reordering in Spin1

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#132]
Flexspin sorts like this: OBJ, long, word, byte
How other spin compilers sort: long, word, byte, (align), OBJ

Trying to "fix" this AFAIU would also require fixing that issue where arrays can't be sized based on constants of an object after them, seems complicated, so uhh.

This isn't a showstopper for #131, but will result in suboptimal code since access to `VBASE+(n<#7)*4` (read: first 8 longs) can use special short opcodes. ASM output may also get a bit smaller by fixing the order in cases where objects with big VAR sections are present (since the VAR offsets in the object containing the big object will more likely fit into an immediate)

**Comment by Wuerfel21** [comment]
Correction: It seems OBJs are not reordered relative to the VARs at all?

**Comment by Wuerfel21** [comment]
Or only sometimes? Ok this is getting confusing.

**Comment by totalspectrum** [comment]
I'll try to take a look at this, but it may be a little while. I'd like to fix the OBJ ordering problem anyway.

**Comment by totalspectrum** [comment]
I think I have fixed this on github now so that objects in Spin always come after variables. Note that in the other languages I've left the ordering alone, I think some C programs rely on variables being declared in order.

**Comment by Wuerfel21** [comment]
IIRC in C variable ordering is explicitly undefined by the standard, but some programs do indeed rely on it. GCC has a flag for it. But yeah, leaving it alone is probably fine
