### ISSUE TITLE
Incorrect handling of label address in constant expression

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#136]
```spin
PUB main
outa := constant(@lbl)
DAT
lbl long 1
```
Compiles to `mov	outa, ptr__dat__` instead of expected `mov	outa, #0`.
In a `CONSTANT` expression, the @ operator should return a relative address.

**Comment by Wuerfel21** [comment]
I think the fix for this is to enable PASM_FLAG when calling `EvalExpr` on a CONSTANT, but idk where the right place to do that is.

**Comment by Wuerfel21** [comment]
Also, in these cases, AST_CONSTANT doesn't actually return true for `IsConstExpr`, which seems like a very bad thing to ever happen.

**Comment by totalspectrum** [comment]
I think this is fixed now.
