### ISSUE TITLE
Regression: unnecessary cog code emitted

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#137]
Just tried building Spin Hexagon again. In addition to #99 still being a thing, there's some new wastes of cog RAM that push it over the edge of failing compilation (reducing FCACHE size makes it fit again, but that's lame).
I think the issue is that feature flags are set for features that aren't actually used.

- some code that allocates a lock is compiled near the beginning. Aside from wasting 4 longs, this also wastes a lock for no apparent reason?
```
	locknew	__lockreg
	wrlong	__lockreg, ptr___lockreg_
```
- some function `gosub__` that is never used
- As said, #99 still happens
- There's also some stuff that apparently handles the case of ABORT-ing without a catch, but that's justified.

**Comment by totalspectrum** [comment]
Actually the features were being output all the time. That's fixed in github now, with feature checks for the lockreg and gosub code.

**Comment by Wuerfel21** [comment]
Many thanks, now Spin Hexagon builds again.
