### ISSUE TITLE
Incorrect Spin main function

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#139]
```
PRI main
dira[2]:=1  
repeat
PUB firstpub
dira[3]:=1
main
repeat
```
The main function in Spin is supposed to be the first PUB function, but flexspin uses the first function regardless of visibility as the main function.

**Comment by totalspectrum** [comment]
Whoops! Funny that nobody has noticed this before now. It's fixed in the master branch now, thank you.

**Comment by Wuerfel21** [comment]
That implementation seems a bit rickety though - won't it return the laste private function if the object doesn't have a public function? I mean that's a completely theoretical scenario, but still.

**Comment by totalspectrum** [comment]
No, it'll keep looping until "pf" is NULL or until a public function is found, so it will return either NULL or a public function.
