### ISSUE TITLE
spin2cpp with --asm should handle spr[..] (Special Purpose Register Array) expression

### ISSUE THREAD

**Issue by dgately** [totalspectrum/spin2cpp#14]
spin2cpp with --asm option cannot handle the Special Purpose Register array of Spin. C & C++ builds work, but not PASM...  Should be a simple fix as SPR array elements exist in PASM already, just need to relate them to the str array elements.

Source:
`temp := spr[8+module]                        ' Copy existing CTR register`

Error:
`SquareWave.spin:32: error: Cannot handle expression yet`

Prop Manual SPR Details:
<img width="756" alt="spr" src="https://cloud.githubusercontent.com/assets/3009364/14058239/6a6086f2-f2d7-11e5-9df5-3c9782d59839.png">

**Comment by totalspectrum** [comment]
I think this is working now.
