### ISSUE TITLE
Incorrect Spin assignment operator overflow behavior with small variables

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#143]
```spin
VAR
long x
byte b
PUB ohno
b := 255
x:=b+=1
```
PropTool and Homespun will set x to 256
Flexspin will set x to 0

**Comment by totalspectrum** [comment]
This one seems like a bug in PropTool/Homespun to me... how could the expression (b+=1) ever be more than  255 when b is a byte?

**Comment by Wuerfel21** [comment]
Because the value of an assignment expression is the 32 bit result of the assignment operator, not the new value of the assigned variable.  Maybe a better example would be `x:=b:=512`, which sets b to 0 and x to 512.

Note that `b++` and the other inc/dec operators do return properly masked values.

**Comment by totalspectrum** [comment]
This is odd behavior from Spin1, and I don't think flexspin will ever follow it. For flexspin, a := b := c is identically the same as b := c followed by a := b.

I've documented the difference. I'll leave the bug open for now, but I'm really tempted to say this is working as intended.

**Comment by Wuerfel21** [comment]
The bytecode backend actually handles this correctly

**Comment by totalspectrum** [comment]
The bytecode backend works for Spin, but probably not for C and BASIC. The PASM backend should work for both now, thanks to a high level transformation on the AST. We need to do something similar for the bytecode to handle the C/BASIC case.

**Comment by totalspectrum** [comment]
I think this is actually working correctly even in bytecode and in BASIC (I just tested with some small test programs)
