### ISSUE TITLE
Spin2? signx= operator using wrong values for 'y' term

### ISSUE THREAD

**Issue by ironsheep** [totalspectrum/spin2cpp#145]
pNut/PropTool uses **signx=** [0-31] for the 'y' term while flexprop appears to be using [1-32]
(check **zerox=** too)

After a number of times not paying attention but finally noticing that when I switched compilers my sign extension wasn't working I finally noticed this issue.

I checked with Chip.  He indicates that this might have been different in P1.

**Comment by totalspectrum** [comment]
Thanks for the bug report, this is fixed now in github. The SIGNX and ZEROX operators themselves were OK, it was only the SIGNX= and ZEROX= variants that were wrong, so a work around for older flexspins is to write "s := s SIGNX y" instead of "s SIGNX= y".
