### ISSUE TITLE
Spin1 assignment-sign-extend missing

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#147]
`~~x` as a statement should word sign-extend `x`, but does nothing in flexspin

**Comment by Wuerfel21** [comment]
Related issue: `y := ~~x` should also write the sign-extended value back into x, but currently doesn't.

**Comment by totalspectrum** [comment]
Thanks for noticing this... funny that it hasn't come up before! I've pushed a fix.

**Comment by Wuerfel21** [comment]
Have you got a check in there to skip the writeback if it'd be a no-op?

**Comment by Wuerfel21** [comment]
Also, uh, there's a test that fails

**Comment by totalspectrum** [comment]
Aargh. Fixed the failing test (serves me right for thinking this was a "simple" change... I tested it a few stand-alone program but didn't check the main tests).

No, there isn't a check for skipping the writeback. I think that would be a useful global optimization, but I'm not quite sure where to put that.

**Comment by Wuerfel21** [comment]
Also: cases where the extended value has side effects, like `~~long[x++]`, don't work

**Comment by totalspectrum** [comment]
OK, I think this is really fixed now. Thank you for your help.
