### ISSUE TITLE
Inaccurate ExprType

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#157]
The result of `ExprType` for `byte[0]-1` in Spin is an unsigned byte, which I think is incorrect (if the byte is zero the expression evals to -1).

Found this while trying to write an optimization to convert unsigned limit ops to signed ones where appropriate

**Comment by totalspectrum** [comment]
Oops, not quite sure why this happened but it does sound wrong. I've checked in a fix.

**Comment by Wuerfel21** [comment]
yep, seems to work as intended now
