### ISSUE TITLE
Is this the same spin2cpp that lives in propgcc?

### ISSUE THREAD

**Issue by bweir** [totalspectrum/spin2cpp#16]
Hi there,

I just stumbled across this after someone suggested adding fastspin to PropellerIDE.
https://github.com/parallaxinc/propgcc/tree/master/spin2cpp

This one certainly seems to have evolved more than the one in propgcc. Can you tell me the chronology of this application and which one I should target?

**Comment by totalspectrum** [comment]
The one here (under totalspectrum) is the master copy. It does not depend on propgcc. In C mode it's intended to be useful for any C compiler (I've used Catalina, and for code that doesn't depend on Propeller hardware the output can be compiled by Visual C on Windows or gcc on Linux). There's also a PASM output mode, which can produce assembly code or even an executable binary.

Someone added a copy to propgcc to make it easier for people porting Spin code to C, but the one here is the one you should use.
