### ISSUE TITLE
Make C/C++ inline assembly more legible by adding whitespace

### ISSUE THREAD

**Issue by DavidZemon** [totalspectrum/spin2cpp#17]
What do you think about adding lots of whitespace to the end of every inline-assembly line? Make this:

```
"		.section .FullDuplexSerial.cog, \"ax\"\n"
"		.equ	EOL, $a\n"
"		.compress off\n"
"..start\n"
"		.org	0\n"
"\n"
"entry\n"
"		mov	t1, PAR\n"
"		add	t1, #(4 << 2)\n"
"		rdlong	t2, t1\n"
"		mov	rxmask, #1\n"
"		shl	rxmask, t2\n"
```

become this

```
"               .section .FullDuplexSerial.cog, \"ax\"                    \n"
"               .equ    EOL, $a                                           \n"
"               .compress off                                             \n"
"..start                                                                  \n"
"               .org    0                                                 \n"
"                                                                         \n"
"entry                                                                    \n"
"               mov     t1, PAR                                           \n"
"               add     t1, #(4 << 2)                                     \n"
"               rdlong  t2, t1                                            \n"
"               mov     rxmask, #1                                        \n"
"               shl     rxmask, t2                                        \n"
```

This copy/paste exercise has also made me aware that tabs are being used in the inline assembly section instead of spaces. I suspect changing that would be a prereq, or else trying to line up the newline and closing quote characters at the end of the lines won't be possible on different editors.

**Comment by totalspectrum** [comment]
That's a great idea. The current master branch has this now -- if you get a chance could you give it a try and let me know what you think of the formatting? Thanks, Eric

**Comment by DavidZemon** [comment]
Just tried it and it looks excellent! Thank you! I think if #18 is ever completed, the line length should probably be bumped to 80 or even 120, instead of what appears to be maybe 70? But without comments, 70 is plenty long enough.
