### ISSUE TITLE
Spin1 sign-extend broken again

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#172]
This seems to be the reason fftbench is slower. It seems that `~~x` in an expression doesn't actually assign back to `x`, which causes the optimization into the actual sign-extend bytecodes to fail, falling back on SHL+SAR. I think this worked at some point??

**Comment by Wuerfel21** [comment]
I think changing the `AstOperator`s in lines 1487 and 1493 of `spin.y` to `AstOpAssign` makes it work

**Comment by Wuerfel21** [comment]
Though presumably that'd break extending short variables in an expression due to #143 ?

**Comment by totalspectrum** [comment]
Ah, I think I see now -- I had disabled the assigning back because that's what was causing fft_bench to spew out too many numbers. But you're suggesting that it's the combination of this bug and #143 that was causes the spew: if both bugs are present fftbench is OK, and if both are fixed fftbench will be OK, but with just one or the other the output is wrong?

**Comment by Wuerfel21** [comment]
No, since fftbench doesn't actually care about the back-assignment, since it's extending from word-sized arrays. So fixing only #143 would not affect it. It's just that when the sign-extend is internally an assignment, the PASM backend will wrongfully read the written back value (which is just the unextended value again)

**Comment by totalspectrum** [comment]
I think this is finally fixed properly, both in the PASM and C++ backends. However, it's quite likely that the bytecode backend is not properly compiling C and BASIC "a = b = c", which require appropriate narrowing/widening to take place. I plan to look at this later, I think a transformation similar to that we do in the PASM backend can fix this.

**Comment by totalspectrum** [comment]
Oops, the "a=b=c" issue is actually #143.
