### ISSUE TITLE
repeat i final value differs from official compiler

### ISSUE THREAD

**Issue by totalspectrum** [totalspectrum/spin2cpp#178]
In something like repeat i from 1 to 5, i has the value "5" in PNut, but "6" in flexspin. We should save the final value off in a temp variable and make sure the loop variable gets set to that afterwards.

**Comment by Wuerfel21** [comment]
Have to, anyways. From what I can divine from the interpreter, end and step are only evaluated once in Spin2. Not sure what flexspin currently does.

**Comment by totalspectrum** [comment]
This was somewhat controversial on the forums. It appears to be a Spin1 / Spin2 difference, and some have suggested that Chip change it back to the Spin1 behavior (same as flexspin's). So not going to change this yet.
