### ISSUE TITLE
Include assembly comments when moving DAT section into inline-assembly in C/C++ file

### ISSUE THREAD

**Issue by DavidZemon** [totalspectrum/spin2cpp#18]
Comments are being stripped from the DAT section of Spin files when converting to C/C++. It'd be great if they could be left in the code.

**Comment by totalspectrum** [comment]
This is a good idea. Unfortunately the parser has always discarded comments in the DAT, so re-tooling it to handle them is probably a bit of work. I'll leave this open though to remind us that it's something we should do.

**Comment by totalspectrum** [comment]
As of version 3.4.0 the comments are kept in inline assembly if --gas is used. The comments actually come out as C/C++ comments in front of the inline assembly, but I think this should work OK.
