### ISSUE TITLE
Spin DEBUG seems to be broken right now

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#185]
Tried to test how the current Spin debug interacts with BRK-based PASM debug. Uhhhhhhmmmmm...

```spin
CON
_CLKFReQ = 10_000_000
PUB main()
repeat
  debug("Aww yiha!")
```

gives me
```
$ ./flextest -2 -g --verbose debug.spin2
Propeller Spin/PASM Compiler 'FlexSpin' (c) 2011-2021 Total Spectrum Software Inc.
Version 5.9.2-beta-v5.4.3-550-g597ebbe7 Compiled on: Sep  5 2021
debug.spin2
fmt.c
error: No implementation for `__lockio' found in `libsys/fmt.c'
error: No implementation for `__unlockio' found in `libsys/fmt.c'
```

Unrelatedly, which symbol presets the baudrate for the built-in serial functions again? I know I can call `_setbaud`, but I recall there being a CON that can be defined...

**Comment by totalspectrum** [comment]
I can't reproduce this:
```
$ flexspin -2 -g --verbose debug.spin2
Propeller Spin/PASM Compiler 'FlexSpin' (c) 2011-2021 Total Spectrum Software Inc.
Version 5.9.2-beta-HEAD-v5.4.3-550-g597ebbe7 Compiled on: Sep  5 2021
debug.spin2
fmt.c
debug.p2asm
Done.
Program size is 3824 bytes
```
And it runs as expected. Is it possible your build system has some stale files? Perhaps try a "make clean". 

As for the symbol, -D_BAUD=nnnn on the command line sets the default baud rate. This is a command line define though, not a CON symbol.

**Comment by Wuerfel21** [comment]
Oh, that seems to be the case, my include dir was outdated... >_>
