### ISSUE TITLE
BRK debugging for high-level languages

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#186]
Aside from the printf-type debug not playing nice with the BRK debug as-is, it'd be nice to run both PASM and high-level DEBUG through the BRK system. And I don't think the printf implementation supports the array functions?

I figured out what is needed:
 - change code in `spin.y` to emit `AST_BRKDEBUG` when `gl_brkdebug` is set.
 - Add a new `bool spinmode` parameter to `AsmDebug_CodeGen` that makes it omit the `DBC_ASMMODE` and the parameters (fetched from stack in Spin mode).
 - Compile the `AST_BRKDEBUG` like a stack call, but then reset ptra (the debugger fetches arguments from `++ptra`), and do a BRK (obtain the ID from `AsmDebug_CodeGen`).

I post this as an issue because looking at the relevant code in `outasm.c` makes me think that I'd be likely to break it trying to implement this. And the other changes needed are fairly trivial.

**Comment by totalspectrum** [comment]
I've kind of implemented this, although I didn't try to use Spin mode -- I just kept everything in DEBUG mode and saved the values I wanted printed into registers. It seems to work fine for normal PASM output. For the nu bytecode output I'm getting garbage output from the debug statements, and I can't quite figure out why.

**Comment by totalspectrum** [comment]
Ah, I found the -gbrk problem with nu: the nu output .p2asm file didn't have a _clkfreq constant defined. Fixed now.

Is there any way we could pass the baud rate to the debug stub?

**Comment by Wuerfel21** [comment]
Yes, that's implemented, just set `DEBUG_BAUD`

**Comment by Wuerfel21** [comment]
Or you mean at runtime? I think that's possible, just need to add a new "simple" opcode to facilitate that. Not sure if the conversion from actual baud to pin config should be in the debug blob or the user code. Relatedly, we probably want to not have the CogN output for that break. I think that could just be generalized with a new `DEBUG_` keyword that'd just cause the CogN printing opcode to not be emitted.

**Comment by Wuerfel21** [comment]
Funnily enough, the baudrate was why the Zoom demo of the debug thing went so wrong. For some reason I had to explicitly set it, the default for some reason didn't work properly? Should investigate that. Also got it to segfault, so should probably investigate that, too.

**Comment by Wuerfel21** [comment]
(Also, considering Nu is stack-based, wouldn't Spin mode be much more natural for it?)

**Comment by totalspectrum** [comment]
I think it's patched now so that a _BAUD define will also set the debug baud rate.

As for Spin more vs Asm mode, the Nu stack is cached in COG memory, so it'd take some copying to get it into the ptra place the debug code expects. So I don't think there's much advantage either way.

**Comment by totalspectrum** [comment]
Thanks again for doing the BRK debug, I think it's a great addition to the tools!

**Comment by Wuerfel21** [comment]
> Funnily enough, the baudrate was why the Zoom demo of the debug thing went so wrong. For some reason I had to explicitly set it, the default for some reason didn't work properly (I'm very sure it did at some point)? Should investigate that.

Just did, seems that loadp2 just doesn't like opening terminal at 2Mbaud? Again, very sure that worked at some point. Probably a "works on my machine" sorta deal.
