### ISSUE TITLE
fastspin/spin2cpp crashes on recent Mac OS X versions

### ISSUE THREAD

**Issue by dgately** [totalspectrum/spin2cpp#19]
I know, I'm kicking-over an old issue here, but I do think this is a real issue for spin2cpp on Mac OS X. Hopefully another Mac OS X user will have run into this as well and may have more info...

When I run fastspin or spin2cpp on any .spin file, I get a crash at the same place in assemble_ir.c (@ line: 127). The error occurs in this code:

`void
PrintOperandAsValue(struct flexbuf *fb, Operand *reg)
{
    Operand *indirect;

```
switch (reg->kind) {   // reg->kind is pointing to some 'illegal' location in memory`
```

The error in Mac OS X crash-speak is:
`Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000011628be0

VM Regions Near 0x11628be0:
--> 
    __TEXT                 000000010e6cc000-000000010e712000 [  280K] r-x/rwx SM=COW  /Users/USER/*

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   fastspin                        0x000000010e6f0c40 PrintOperandAsValue + 16 (assemble_ir.c:127)
1   fastspin                        0x000000010e6f19a8 DoAssembleIR + 3016 (assemble_ir.c:511)
2   fastspin                        0x000000010e6f210b IRAssemble + 139 (assemble_ir.c:569)
3   fastspin                        0x000000010e6eb0af OutputAsmCode + 1023 (outasm.c:3841)
4   fastspin                        0x000000010e6ce23c main + 5084 (fastspin.c:559)
5   libdyld.dylib                   0x00007fff973d45ad start + 1`

I have tried to debug this problem with lldb and what I see is that that bit of code runs without issue through a number of iterations of parsing through the source until what I think is the last operand, before failing. Is the code perhaps falling through the end of the source? I have tried numerous lldb runs to determine where in source the parsing process is when the failure occurs but am not able to decipher that location.

Is it possible that the compiler (clang) version on Mac OS X 10.11.6 defines some variable at a different size, that may allow this issue to arise?

**Comment by totalspectrum** [comment]
I tried building with clang on Linux, and all the tests worked fine. So I don't think it's a compiler specific issue. Does version 3.2.0 (the current master branch) work for you on Mac OS X?

**Comment by dgately** [comment]
On Mac OS X Sierra, rebuilt spin2cpp with latest branch and was able to create .c & .h files from simple .spin file. So far looks good! Will test a bit more before closing...

**Comment by dgately** [comment]
Exec'd spin2cpp on several existing spin projects and have been able to create buildable C projects!... Closing this bug report.  Thank you!

**Comment by totalspectrum** [comment]
Great! Thanks for testing this Dennis.
