### ISSUE TITLE
REP optimization breaks BRK debug

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#190]
```spin
CON
_CLKFREQ = 100_000_000
DEBUG_BAUD = 115200
PUB main() : i
repeat
  debug("onek",udec(i++))
```
The loop gets compiled into a REP instruction, which prevents the BRK interrupt from firing.

**Comment by totalspectrum** [comment]
Whoops, yes, that is wrong. It should be fixed now, thanks!
