### ISSUE TITLE
Spin2: ALIGNL / ALIGNW in VAR section unimplemented

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#195]
Spin2 allows aligning in VAR sections. Flexspin syntax-errs.

Don't beat yourself up though, PropTool's syntax highlighting doesn't know what's going on, either...

![image](https://user-images.githubusercontent.com/6944842/135536763-8fd6b9e7-1c13-47d5-a414-08c2f8960de0.png)

**Comment by totalspectrum** [comment]
Thanks for noticing this. It should work now.
