### ISSUE TITLE
Spin2cpp failing to convert Scribbler S3 code

### ISSUE THREAD

**Issue by DavidZemon** [totalspectrum/spin2cpp#20]
[Scribbler Default V2579.zip](https://github.com/totalspectrum/spin2cpp/files/491354/Scribbler.Default.V2579.zip)

I ran spin2cpp over each of the source files in the attached zip: `find . -name '*.spin' -exec spin2cpp --gas {} \;`.

This fails on scribbler_test.spin, first at line 121:
```
david@balrog:~/Desktop/S3 Open Source/Software$ find . -name '*.spin' -exec spin2cpp --gas {} \;
./scribbler_test.spin:121: error: Unknown symbol TEST_LED
./scribbler_test.spin:121: error: Unknown symbol TEST_LED
```

It seems to require that `TEST_LED` be defined before its usage on 121. I moved it up above it's usage on 121 and life is good. Upon trying to rerun spin2cpp over the file, I get a new error:
```
david@balrog:~/Desktop/S3 Open Source/Software$ spin2cpp --gas scribbler_default.spin 
scribbler_test.spin:1365: error: expected identifier after '.'
scribbler_test.spin:1366: error: expected identifier after '.'
scribbler_test.spin:1367: error: expected identifier after '.'
```

At this point, C++ source code is generated, but is faulty. The original Spin on lines 1365-1367 is

```
    print_dec_word(constant(GRAPH_COL_START+9),constant(TOP_MARGIN+1),left[index] := scribbler.light_sensor_raw(scribbler#LEFT))     
    print_dec_word(constant(GRAPH_COL_START+9),constant(TOP_MARGIN+2),center[index] := scribbler.light_sensor_raw(scribbler#CENTER))
    print_dec_word(constant(GRAPH_COL_START+9),constant(TOP_MARGIN+3),right[index] := scribbler.light_sensor_raw(scribbler#RIGHT))           
```

But the generated C++ does not pass the `scribbler#LEFT` parameter to the `light_sensor_raw()` method:

```
    print_dec_word(0x9, 0x5, (left[index] = scribbler.light_sensor_raw()));
    print_dec_word(0x9, 0x6, (center[index] = scribbler.light_sensor_raw()));
    print_dec_word(0x9, 0x7, (right[index] = scribbler.light_sensor_raw()));
```

**Comment by totalspectrum** [comment]
I think these are fixed in the 3.2.0 version.
