### ISSUE TITLE
Second instance of a serial object doesn't function when using the bytecode backend

### ISSUE THREAD

**Issue by avsa242** [totalspectrum/spin2cpp#202]
Hi guys...I've been testing out the P1 bytecode backend (`--interp=rom`) for a little over a month now and I have to say, before this, I haven't run into any bugs. It really seems to work pretty well so far - nicely done!

What I _have_ run into is an issue when more than one serial object is declared. The second instance doesn't seem to function, at least under certain circumstances. The cog _does_ seem to start, but there is no output from the second object (confirmed both by no visible characters on the second terminal as well as the TX LED not blinking on the Prop Plug).
This is the test code:

```spin
CON

    _clkmode = xtal1 + pll16x
    _xinfreq = 5_000_000

OBJ
' The instance declared with the "ser" symbol functions properly, and the 'test' string is displayed.
' The "com" instance does nothing, however.
    ser: "FullDuplexSerial"
    com: "FullDuplexSerial"

PUB Main | pstr

    ser.start(31, 30, 0, 115_200)
    com.start(23, 22, 0, 115_200)
    waitcnt(cnt+clkfreq/10)
    pstr := string("test")

    ser.str(pstr)
    com.str(pstr)

    repeat

```

I've tried two other variations of the above, and that is to declare an array of two `ser` objects (i.e., `ser[2]: ...`) as well as renaming `com` to `fds`, in case there was somehow a collision with an undocumented reserved word. These operated the same way.
I usually use a derivative of FDS, so thought it might be an issue there, but as above, I've tested with Parallax's FDS, and the issue is the same.

The snippet operates correctly when built with OpenSpin (dead code removal enabled), as well as the native-code backend of FlexSpin.

**Comment by avsa242** [comment]
gah...disregard, right after I posted this, I found a hardware issue - sorry :( !

**Comment by Wuerfel21** [comment]
Awww, this would've been the first bytecode bugreport ;)

But I'm curious as to how a hardware issue would cause the flexspin binary to not work where the openspin one does?

Also, cute tip: you can do `@"test"` instead of `string("test")`

**Comment by avsa242** [comment]
Sorry, I'm not sure why I said hardware (unless you count the human brain driving the fingers...) - it was in fact a software config issue. Too many boards on the bench, and I simply had proploader setup to talk to the wrong one. *blush*

That said, there *is* a string()/strsize() issue I ran into a week or so ago that I'm confident is a real bug, but I was in too much of a hurry at the time and didn't make a record of what was causing it. I'll see if I can find the code that caused it and open a new issue soon.
Thanks for the @"test" tip...wasn't aware of that!
