### ISSUE TITLE
spin1 bc: string() with symbols as params fails to build; numeric constants ok

### ISSUE THREAD

**Issue by avsa242** [totalspectrum/spin2cpp#206]
Hey guys,

Just came across this one this morning:

```spin
CON

    LF  = 10
    CR  = 13

PUB Main

    second(string(CR, LF))      ' fails
    second(string(13, 10))      ' OK

PUB Second(param1)
```
The compiler errors out with `error: Unhandled AST kind 4 in string expression` on the first call above, but builds successfully if using the second line as a workaround.
This only seems to affect the bytecode backend; building to native code works (tested with OpenSpin and Propeller Tool and it's legal there, too).

Cheers

**Comment by Wuerfel21** [comment]
Yep, string builder code is for some reason separate for BC mode and it doesn't handle anything that's not a string or integer literal.

Hmmm, adding support for arbitrary integer expressions shouldn't be an issue, but maybe it would be better to refactor the whole thing to share the same string building code from the other backends.

**Comment by totalspectrum** [comment]
I think the backends are kind of ad-hoc right now, so I've fixed the bytecode emitter to handle constant expressions. Thanks for the bug report, Jesse.
