### ISSUE TITLE
gbrk oversight: debug functions are variadic, actually

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#207]
In PNut/proptool `uhex_long(pa,pb)` is valid and equivalent to `uhex_long(pa),uhex_long(pb)`

Considering that no one noticed this before, either no one knows about this being a feature in PNut or no actually uses -gbrk. (not sure if -g software debug supports this, either, too lazy to check RN).

This also seems to work for debug functions with multiple arguments, but of course the arg count must be a multiple of the expected count.

**Comment by totalspectrum** [comment]
The old -g software debug did support it, so it was just -gbrk that needed fixing. I've pushed what I think is a basic fix; it makes a simple test work right, anyway. Thanks for the bug report.
