### ISSUE TITLE
-gbrk and _FREE/_STACK

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#208]
Here's something I've just thought of: Do these features interact correctly?

With the debugger loaded, there's 16K RAM missing, that should be taken into account. But the debugger blob and its data disappear after startup, so they should not count towards the size (I think they currently do).

**Comment by totalspectrum** [comment]
There was a bug, -gbrk should reduce the available memory by 16K (as you said). The size of the debugger blob isn't included in the totals (it's appended later) so I think that part is OK. I've updated the calculations, thanks.
