### ISSUE TITLE
spin1 bc: case in child object method, no cases match

### ISSUE THREAD

**Issue by avsa242** [totalspectrum/spin2cpp#209]
Hi guys,

I came across this one this morning; as the title says, when building bytecode, if there is a `case` in a child object method, no cases seem to match. In this example code:

```spin
' parent.spin
CON

    _clkmode = xtal1+pll16x
    _xinfreq = 5_000_000

OBJ

    ser: "FullDuplexSerial"
    ch : "child1"

PUB Main

    ser.start(31, 30, 0, 115200)
    waitcnt(cnt+clkfreq/2)
    ser.dec(ch.method1(100))
    ser.dec(method1(100))

PUB method1(p1): r1

    case p1
        0..100:
            return 1
        other:
            return 2
```

```spin
' child.spin
PUB method1(p1): r1

    case p1
        0..100:
            return 1
        other:
            return 2

'    if p1 => 0 and p1 =< 100
'        return 1
```
In the child's copy of `method1()`, neither the `0..100:` or the `other:` case match, so the method always returns 0. However, the parent's copy of the same method returns the expected value.
When built to native code, all appears ok.
The `if` equivalent code seems to work. I tried `case_fast`, which also seemed to work correctly.

Cheers!

**Comment by Wuerfel21** [comment]
The generated bytecode for both methods seems to be correct and identical (save for different offset of the non-matching case). There's no possibility that it could fall through, so something must go wrong with the call?
```
'--- Function method1
0290: 38 17                   ' FUNDATA_PUSHADDRESS +23
0292: 64                      ' MEM_READ LONG DBASE+$0004 (short)
0293: 35                      ' CONSTANT 0
0294: 38 64                   ' CONSTANT 100
0296: 0E 02                   ' CASE_RANGE +2
0298: 04 02                   ' JUMP +2
'LABEL
029A: 36                      ' CONSTANT 1
029B: 33                      ' RETURN_POP
'LABEL
029C: 38 02                   ' CONSTANT 2
029E: 33                      ' RETURN_POP
'LABEL
029F: 32                      ' RETURN_PLAIN
```

**Comment by Wuerfel21** [comment]
Infact, yes, something is going very wrong with the call.
```
003B: 01                      ' ANCHOR  (DISCARD)
003C: 38 64                   ' CONSTANT 100
003E: 06 04 01                ' CALL_OTHER 4.1 (ch.method1)
```

**Comment by Wuerfel21** [comment]
Can't figure out how a function parameter would ever be compiled as a non-expression though.

**Comment by totalspectrum** [comment]
For some reason the compiler thinks the child method does not return anything. Something in the optimizer is going awry. A work-around is to insert "return 0" at the end of the function, or r1 := 0 at the start (before the case). I don't understand why child and parent methods are being treated differently this way, though!

**Comment by Wuerfel21** [comment]
Ahhh, so it's not the bytecode part :)

Though this transform is really stupid in bytecode mode, a function that returns nothing really returns zero, so discarding that and manually pushing a zero is somewhat pointless.

**Comment by avsa242** [comment]
It seems weird I haven't come across this yet...I often use `case` in child objects that return values, and I think I've been using the bytecode backend of FlexSpin for a few months now. The native code backend works fine, though.

Confirmed that initializing the return value to 0 at the method start works (which I think I really should be doing anyway...I'm usually in the habit of doing this, but for some reason didn't in the method that precipitated this).

**Comment by totalspectrum** [comment]
I've added a check to just always assume the result is used in bytecode mode, which I think should fix everything (it does fix the example). The source is checked in to github. Thanks for your help!

**Comment by avsa242** [comment]
Confirmed in the original code too, thanks!
