### ISSUE TITLE
Add a -v (or --version) option to allow identification of spin2cpp version

### ISSUE THREAD

**Issue by dgately** [totalspectrum/spin2cpp#21]
It would be helpful to add a version option in all the built binaries from the spin2cpp distro. This allows developers to know that they are using a specific version, as spin2cpp matures.

**Comment by drawkula** [comment]
It kind of is already there...

    $ /opt/spin2cpp/bin/spin2cpp |& head -1
    Spin to C++ converter version 3.2.0

...but I think `--version` would be even better... ;-)

**Comment by totalspectrum** [comment]
Thanks for the suggestion. I've added --version (and a synonym, -v) to spin2cpp, which prints the version to stdout and then exits immediately. fastspin already has the -h option (the same as openspin's) so I'm leaving that one alone for now.
