### ISSUE TITLE
[BASIC] declare alias vs [1BC]

### ISSUE THREAD

**Issue by drawkula** [totalspectrum/spin2cpp#211]
Thanks for allowing constants in `declare alias`!  
I noticed a small glitch?   
Or is it incompatible with the bytecode mode by limitations of bytecode?

```
$ cat declare-alias.bas 
declare HubAsUbytes alias 0 as ubyte(32768)

for i=0 to 15
  print " ";HubAsUbytes(i);
next
print
```
Compiled as 1LMM:
```
$ /opt/propellertools/bin/flexspin declare-alias.bas 
Propeller Spin/PASM Compiler 'FlexSpin' (c) 2011-2022 Total Spectrum Software Inc.
Version 5.9.7 Compiled on: Jan 30 2022
declare-alias.bas
fmt.c
declare-alias.pasm
Done.
Program size is 2688 bytes
```
Compiled as 1BC:
```
$ /opt/propellertools/bin/flexspin -1bc declare-alias.bas 
Propeller Spin/PASM Compiler 'FlexSpin' (c) 2011-2022 Total Spectrum Software Inc.
Version 5.9.7 Compiled on: Jan 30 2022
declare-alias.bas
fmt.c
declare-alias.bas:4: error: Unhandled Symbol type 23 in memop
Program size:     880 bytes
Variable size:      0 bytes
Stack/Free:     31872 bytes
```

**Comment by totalspectrum** [comment]
I was going to say "it's just an oversight"... but when I tried to fix it I got non-working code, so there is indeed an incompatibility with bytecode, of some form. It's probably fixable, but not trivially, so for now it'll have to stay on the lnown bugs list. Thanks for the report!

**Comment by drawkula** [comment]
It is a brand new feature, it can't break a lot of existing code, so there is no hurry.

Thanks!

**Comment by totalspectrum** [comment]
I think this should be working now.

**Comment by drawkula** [comment]
[\o/](http://yeti.freeshell.org/orgy/flexprop/flexprop.html#:flexbasic:example:declare-alias-1) WOW!  That was fast!  THANKS!
