### ISSUE TITLE
Support number seperators in C

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#213]
C++14 (and soon, C23) allows quotes to be inserted to make numerical constants easier to read: `2'000'000`. Would be neat if FlexC had that.

**Comment by totalspectrum** [comment]
FlexC actually does support that; it also supports underscores inside of C constants (like in Spin).

**Comment by Wuerfel21** [comment]
Whoop, should've probably tested it before complaining ;/
