### ISSUE TITLE
C: broken function ptr cast

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#216]
Apparently casting a function ptr like this: `(size_t (*)(void *, size_t, size_t, void *))  fread,` (in a struct initializer) results in `error: incompatible types in assignment: expected function of 4 args returning unsigned int  but got unsigned int`

**Comment by totalspectrum** [comment]
I think this particular problem is fixed now. No doubt there are other ones lurking -- the C type parsing code is a mess :(.
