### ISSUE TITLE
multiply low/high fusing doesn't actually work on P2

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#225]
... because the normal part of the multiply is emitted as a native op and the high part emits a function call.

As seen in some of the system functions:
```
__system___scas
	qmul	arg01, arg02
	getqx	_var01
	mov	muldiva_, arg01
	mov	muldivb_, arg02
	call	#multiply_
	shr	_var01, #30
	shl	muldivb_, #2
	or	muldivb_, _var01
	mov	result1, muldivb_
__system___scas_ret
	ret
```

Not sure how to fix this. Optimizing between function calls and cordic ops seems like it'd cause headaches and the high multiply is quite a lot of code, so just generating it inline is a bit eh. I guess these system functions in particular could be rewritten with inline ASM.

**Comment by totalspectrum** [comment]
Actually I think expanding the high multiply inline isn't too bad, it's not that commonly used on its own. So I've done that.

**Comment by Wuerfel21** [comment]
With the reorder optimization it's probably a big speedup.
