### ISSUE TITLE
DEBUG doesn't work with multi-return functions

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#236]
```
PUB main()
    DEBUG(sdec(test()))
PUB test() : a,b
    return 1,2
```
-gbrk only picks up the first return value, regular -g just kinda dies. This works in prop tool (including passing multi-returns into two-argument debug functions).

**Comment by totalspectrum** [comment]
It should work now for up to 4 return values, which I think should handle most cases.
