### ISSUE TITLE
VGA_HiRes_Text.spin breaks spin2cpp

### ISSUE THREAD

**Issue by cmayer68** [totalspectrum/spin2cpp#24]
nice work, but:

The (pretty amazing) VGA_HiRes_Text.spin that is one of the standard objects gives spin2cpp a bit of trouble.

copies available lots of places: 
https://github.com/alamorobotics/W65c816_VGA/blob/master/VGA_HiRes_Text.spin
http://www.brielcomputers.com/files/VGA_HiRes_Text.spin
http://obex.parallax.com/object/650
https://github.com/parallaxinc/spin-standard-library/blob/master/library/display.vga.text.hires.spin

1) spin2cpp --asm VGA_HiRes_Text.spin SEGV's.

2) spin2cpp --gas VGA_HiRes_Text.spin does not produce a compilable file, as the
assembly overflows the 9 bit offsets. this is probably because org does not work on gas
like it does on pasm.

3) spin2cpp --gas --dat VGA_HiRes_Text.spin hangs in an infamous loop.

all this on mac and linux (64) using the current source.

**Comment by totalspectrum** [comment]
Thank you for the bug reports. I've fixed the spin2cpp --dat --gas hang. I can't seem to reproduce the SEGV though. Do you have gdb? If you could run gdb --args spin2cpp --asm VGA_HiRes_Text.spin and then show the stack trace when it SEGVs that would be very helpful.

Thanks,
Eric

**Comment by totalspectrum** [comment]
I have fixed a bug which was manifested in 64 bit linux (under some conditions a pointer got put into a 32 bit value, which would cause a segmentation fault if the upper bits of the address were non-zero). Perhaps this will fix the issue.
