### ISSUE TITLE
C library in Spin: some functions yield unknown identifier

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#242]
```
VAR
byte lol[256]
OBJ c : "libc.a"
PUB main()
c.strncpy(@lol,@"abc",255)
c.strncat(@lol,@"def",255)
```
`strncpy` is okay, but `strncat` is apparently just too much.

**Comment by drawkula** [comment]
Maybe it really is missing in `libc.a`?

**Comment by Wuerfel21** [comment]
Oh yeah, it isn't in there. I guess that's the bug then.

**Comment by Wuerfel21** [comment]
Also missing: `fseek`, related constants and `rewind`

**Comment by totalspectrum** [comment]
I've added strncat and fseek. Constants are a whole different story (they are #define'd, so not sure how we should get them into Spin.

**Comment by Wuerfel21** [comment]
I just copied them into an enum (which is ok because SEEK_* are defined to have particular values, anyways)
```c
enum {
    SEEK_SET  = 0,
    SEEK_CUR  = 1,
    SEEK_END  = 2,
};
```
