### ISSUE TITLE
Source using post-clear operator fails to build

### ISSUE THREAD

**Issue by avsa242** [totalspectrum/spin2cpp#262]
Hey guys,

The following code:

```spin
pub main | a

    a := 1
    if (a~)
```
fails to build - the compiler bombs out with `error: Internal error, should not see POSTSET in LVS`
Post-clear by itself (not inside an `if`) builds ok.

This is only triggered using the bytecode backend with -O2; lesser or no optimization builds (and works) fine. Native build works fine as well. I thought for sure I'd built code that used the function that first triggered this in the past, but I went as far back as a June something last year build of flexspin and it did it then, too...so I think it's probably been there since the beginning.

Cheers

**Comment by Wuerfel21** [comment]
Yep, -O2 + bytecode -> brap. Always has been. Should probably at least be documented. I think it'd work with `-O2,~loop-reduce`, so maybe try that (or `-O1,cse`). Not sure how useful CSE is to the bytecode backend though.

**Comment by avsa242** [comment]
Ahh, okie doke - yeah it works with -O2,~loop-reduce. FWIW, it does seem to work fine with just about everything else I've built.

**Comment by totalspectrum** [comment]
Thanks for the bug report. For now I just have the code throw up its hands and not try to loop optimize, which is pretty much what -O2,!loop-reduce does anyway.
