### ISSUE TITLE
Setting P1 clock from C enum doesn't work

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#267]
```c
enum {
  _clkmode = XTAL1 + PLL8X,
  _xinfreq = 6'000'000,
};
int main() {
    _OUTA |=1;
}
```
Ends up with the default 80MHz config still. Equivalent Spin program works.

**Comment by Wuerfel21** [comment]
(It does however throw an error if only _clkmode but not _xinfreq is specified, so it's picking it up right I guess?)

**Comment by totalspectrum** [comment]
I think this should be fixed now... the problem was that the C enums aren't copied into the Spin CON table and hence don't make it into the final binary. I've added exceptions for _clkmode and _clkfreq.
