### ISSUE TITLE
BRK Debug is mega broken

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#270]
Should've probably, like, tested it after messing with it.
 - missing break in `case PASM_EVAL_ISREG` causes **all debugs** to emit garbage bytecode
 - the multi-return cases are broken for more than 2 registers (`addr++` should be in loop)
 - multi-return + array opcodes generate garbage bytecode

**Comment by totalspectrum** [comment]
Thanks. There was also a problem with the optimizer removing moves that the break debugger dependend on, which I think has always been there. I think all that should be fixed now.
