### ISSUE TITLE
Optimizer bug

### ISSUE THREAD

**Issue by electrodude** [totalspectrum/spin2cpp#271]
The optimizer should inline the call to `endian2`, assigning `x := $8`, but instead it just zeros `x`:
```spin
VAR
  long x

PUB main
  x := endian2($0800)

PUB endian2(w)
  return w.byte[0] << 8 | w.byte[1]
```

Incorrect assembly listing as of a702db180d4b710b624735bca6823ae216e6bf07 (@Wuerfel21):
```spin2
' 
' PUB main
_main
'   x := endian2($0800)
'   return w.byte[0] << 8 | w.byte[1]
	wrlong	#0, objptr
_main_ret
	ret
```

Correct assembly listing before a702db180d4b710b624735bca6823ae216e6bf07:
```spin2
' 
' PUB main
_main
'   x := endian2($0800)
'   return w.byte[0] << 8 | w.byte[1]
	wrlong	#8, objptr
_main_ret
	ret
```

**Comment by Wuerfel21** [comment]
That's an odd commit to break stuff, given that it just fixes a really obvious mistake.

**Comment by Wuerfel21** [comment]
Oh, wait, it's missing `break`s in there, isn't it?
