### ISSUE TITLE
Silence "RES has 0 space" warning if value is dynamic

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#276]
Odd that that warning exists, anyways. It pops up when you do stuff like `res (4-($&3))&3` to align some values in memory (for ALTI wrap mode fun times)

**Comment by totalspectrum** [comment]
At the point where the warning is issued we don't know if it's dynamic or not. But I've added a check to suppress the warning if it's being calculated with &, which I think most alignment would be.
