### ISSUE TITLE
New SD code breaks NeoYume

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#280]
![Screenshot 2022-06-06 00-42-15](https://user-images.githubusercontent.com/6944842/172073706-755a914b-e00c-41c3-ae8a-bea55d4bd7fd.png)

Very cool.

MegaYume is fine, oddly enough (they use the FS in similar ways, though NeoYume is actually somewhat simpler (no full file browser)).

The NO GAMES message happens when it can't find any games. The relevant code looks like this:
```spin

dir := c.opendir(@"/sd/NEOYUME/")
ifnot dir
  putstring(@"Directory error:",2,24,0)
  putstring(c.strerror(errno),3,25,0)
  repeat
repeat
  ent := c.readdir(dir)
  ifnot ent
    quit
  name := a.get_name(ent)
  repeat i from 0 to max_count-1
    ifnot c.strcasecmp(name,gamelist[i]+@gamedb_base)
      byte[games_got][i] := 1
      got_count++
      mingot <#= i
      maxgot #>= i
      quit
c.closedir(dir)
tmp := 0
repeat i from 0 to max_count-1
  if byte[games_got][i]
    byte[games_got][i] := ++tmp

ifnot got_count
  putstring(@"NO GAMES!",4,14,0)
  repeat
```
Will try to investigate further, but have this as an initial report.

**Comment by Wuerfel21** [comment]
Strangely, it seems that the directory is enumerated correctly, but the comparsion just never matches

**Comment by Wuerfel21** [comment]
Verified it isn't the database getting corrupted or smth, it seems like strcasecmp got borked.

**Comment by Wuerfel21** [comment]
It seems that it gets the very unwise idea to look up `__ctype` in some offset from `objptr` that isn't actually set on call (o

![image](https://user-images.githubusercontent.com/6944842/172076085-2dab31da-5fe2-48a1-81ef-82c6ecf7c3f9.png)

It also creates all these cool registers that are used exactly once to create one method pointer on the heap.

![image](https://user-images.githubusercontent.com/6944842/172076131-91572f01-f8c1-40f8-b072-470a0bbb07b9.png)

**Comment by totalspectrum** [comment]
It may work now...

The problem was that all C variables were always being defined in the DAT section, which meant that using more than one C object in a program wouldn't work (for example, having more than one SD card). Now most C variables are created like ordinary member variables, except at the top level. But this is a pretty big change, so it's not surprising that some things broke. I've fixed a bunch of problems including the one that broke strcasecmp.

**Comment by Wuerfel21** [comment]
Now we're up to `error: Non-const member variable _sys_errlist cannot be initialized at compile time`

**Comment by Wuerfel21** [comment]
aaand we're up to `error: Unknown type for sizeof`

**Comment by Wuerfel21** [comment]
Seems to work now.

**Comment by Wuerfel21** [comment]
I guess this can be closed for now.

Though pik still has issues with his code overflowing cog ram I think.
