### ISSUE TITLE
Nucode lacks VA support (no sprintf)

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#281]
You probably know this, but I just noticed, so here's an issue.

**Comment by totalspectrum** [comment]
Regular P1 bytecode also has this issue...

**Comment by Wuerfel21** [comment]
True that. Might look into it when the P1 board is hooked up again. Or I guess I could spinsim it (what's the holdup with merging #266 btw?)

**Comment by Wuerfel21** [comment]
(Thinking about it, solution would need to be a bit spicy to avoid shifting all the locals about)

**Comment by totalspectrum** [comment]
The holdup on #266 is just laziness on my part, sorry. I'll get around to it soon I think.

For both bytecode solutions maybe we could do something really nasty like allocating a block on the heap and using that to store the varargs parameters. I thought of __builtin_alloca instead, but freeing the stack memory seems like it would be a pain. Maybe we could restrict varargs functions to having just 1 or 2 return values, that would let us use some scratch registers to hold the return while the stack is being re-adjusted...

**Comment by Wuerfel21** [comment]
Perchance change local order?
Normal function: RESULT, arguments, locals
Theoretical varargs: RESULT,normal arguments, locals, varargs

This would be performed by inserting a longmove at the top of the function... Not ideal, but longmove is reasonably quick.

**Comment by totalspectrum** [comment]
Hacked in some heap allocation in high level code (so the same stuff can be used by any backend that needs it, including for now both bytecode backends). It seems to be working now for nucode and P1 bytecode.
