### ISSUE TITLE
Trapping an abort in a more complex expression terminates FlexSpin

### ISSUE THREAD

**Issue by avsa242** [totalspectrum/spin2cpp#286]
I ran into an issue with an older version of FlexSpin (5.9.11-gitsomething) - was segfaulting when trapping an abort in spin1 on the P1. I updated to the latest and it no longer segfaults but it still terminates unexpectedly.

With the following code:

```spin
pub main

'    if (\method1) == -2     ' OK
'    if \method1             ' OK
    if \method1 == -2       ' failure

    repeat

pub method1

    abort


```

the third case fails (FlexSpin stops with `Command terminated`).
If the portion pertaining to just the abort trap is surrounded with parens (first case), or if the test equality expression is removed (second case), it builds successfully.
(the above is of course contrived - the issue was discovered in code that actually did something)

Other tidbits of info:
* Optimization level seems to have no effect
* Building to native code succeeds
* spin2 native and nu both succeed

Cheers

**Comment by Wuerfel21** [comment]
Don't have time quite now, but here's some insight:

Code for handling catch looks like this...
```c
            case AST_CATCH: {
                BCCompileFunCall(irbuf,node->left,context,!asStatement,true);
                popResults = 0;
            } break;
```
So what I think happens is that the entire expression `method1 == -2` gets placed into the catch statement (i.e. wrong operator priority).

If your building from source, try putting this line at the top of `BCCompileFunCall` (backends/bytecode/outbc.c)
```c
ASSERT_AST_KIND(node,AST_FUNCCALL,return;);
```

**Comment by avsa242** [comment]
Okay, added - here is the output now:

```
trap_abort_cmd_terminated_building.spin:5: error: Internal Error: Expected AST_FUNCCALL got 5 @ backends/bytecode/outbc.c:1629
trap_abort_cmd_terminated_building.spin:7: warning: Optimization pass limit (50) exceeded on function main
Program size:      20 bytes
Variable size:      0 bytes
Stack/Free:     32732 bytes

shell returned 1
```

**Comment by Wuerfel21** [comment]
Yep, that's it, wrong operator precedence.

**Comment by totalspectrum** [comment]
Thanks for the bug report, it should be fixed in github now.
