### ISSUE TITLE
Value not written to hub in assembled function 

### ISSUE THREAD

**Issue by avsa242** [totalspectrum/spin2cpp#289]
Heya...found a pretty bizarre one (for me, at least :) )
In this snippet:

```spin
OBJ

    ser: "SmartSerial"

PUB TempGetData() | temp{[4]}, tscl    ' uncomment extra allocation: code runs OK

    ser.start(2_000_000)
    temp := tempdata()
    tscl := tempscale()    ' comment me out: code runs OK
    ser.dec(temp/10)


PUB TempData(): t

    return 1234

PUB TempScale(): s

    return 1
```

the result of `ser.dec(temp/10)` _should_ be 123, as-is, but instead prints 0 (did an alternate test where I checked for equality to 123 and printed out "good" or "bad", and it fails too, so it's not just a terminal-related issue).

There are a few things that can be done to give the correct result:
1. Allocating more space for the local temp, at least 4 longs total
2. Removing the call to `tscl := tempscale()`
3. Removing the divide op, or changing the divisor to 1
4. Building to NuCode instead of native code

I don't know enough to know the underlying reason why, but # 4 made me curious to look at the assembled output, and it looks like misbehaving variants are missing a write of the data to hub (`wrlong ##1234, fp`), on or about line 145.

**Comment by Wuerfel21** [comment]
Does it work if you use `-O1,~cordic-reorder`?

**Comment by avsa242** [comment]
Nope same result

**Comment by totalspectrum** [comment]
Looks like we were missing a sanity check in an optimization. I think this should be fixed in github now. Thanks for the bug report, Jesse!

**Comment by avsa242** [comment]
Confirmed, thanks!

**Comment by Wuerfel21** [comment]
Hmm, looking at the fix, shouldn't `FindPrevSetterForReplace` already fail if any operand of `stop_ir` is modified? Hmm. Though `ModifiedInRange` is rather aggressive, so it shouldn't cause any missed cases. Though it should probably be `ModifiedInRange(stop_ir->next, ir->prev, stop_ir->src)`?

**Comment by totalspectrum** [comment]
Yes, I think you're right Ada. The proper fix is to use ModifiedInRange inside FindPrevSetterForReplace. I've made that change at 54ce5de1. Thanks!
