### ISSUE TITLE
byte access forces locals-on-stack when inside a memory index

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#292]
Basically, fix from #67 isn't applied when the byte expression is inside a memory index node.
This code does not compile:
```spin
PUB main() | i
i := ina
outa := byte[i.byte[1]]
asm
  mov outb,i
endasm
```

**Comment by totalspectrum** [comment]
Ouch, thanks for finding this. I'll dig into it and try to find a better way to fix #67.

**Comment by totalspectrum** [comment]
I can't remember why the optimization wasn't applied more often, but my guess is that it interfered with an array optimization and I wanted to be cautious. I've enabled it for everything except arrays, and your example compiles & works (and the usual tests all pass).

**Comment by totalspectrum** [comment]
This seems to be workiing now, I think
