### ISSUE TITLE
putchar() does not work in bytecode

### ISSUE THREAD

**Issue by totalspectrum** [totalspectrum/spin2cpp#294]
In P1 bytecode the putchar() function does not work. It almost appears to be waiting for input??

**Comment by Wuerfel21** [comment]
Hmm, from a casual observation, HOW IS THIS EVEN SUPPOSED TO WORK....

First observation I have is that fputc looks like
```
'--- Function fputc
02A3: 00                      ' ANCHOR  
02A4: 64                      ' MEM_READ LONG DBASE+$0004 (short)
02A5: 68                      ' MEM_READ LONG DBASE+$0008 (short)
02A6: 68                      ' MEM_READ LONG DBASE+$0008 (short)
02A7: 3F AC                   ' REG_WRITE 1EC(VBASE)
02A9: 68                      ' MEM_READ LONG DBASE+$0008 (short)
02AA: 38 06                   ' CONSTANT 6
02AC: D0                      ' MEM_READ LONG (POP base)+(POP index) 
02AD: 3F B3                   ' REG_WRITE 1F3(INB)
02AF: 06 0C 07                ' CALL_OTHER 12.7 (_system_.__call_methodptr)
02B2: 33                      ' RETURN_POP
```
In the actual source, it's calling a C function pointer, but it seems to compile to a Spin2-style method pointer??? There are no heap allocations, so idk where that is even supposed to come from. Also note that there's a VBASE set which is completely pointless on a method pointer call. IOW something's afoot.

What a mess just to print characters.

**Comment by totalspectrum** [comment]
The function/method pointer stuff does work, there are BASIC tests for it. C function pointers are the same as Spin2 method pointers, and are handled in bytecode by the call_methodptr routine (which does some direct hackery with the interpreter registers to accomplish its task).

What's going wrong with putchar() is that the __getftab function is returning the wrong address for &__filetab[i]; it appears that the calculation is being done as if the array contains LONGs, but it's actually an array of 48 byte structs. If you use `fputc(c, stdin)` instead of `putchar()` (which is `fputc(c, stdout)`) then it works, because stdin is at offset 0 (and our library does set up stdin to have a write routine, which is probably wrong but helps in this case).

Not sure why VBASE is being pushed in fputc though, that does seem redundant...

**Comment by totalspectrum** [comment]
I think I've got the address calculation fixed, and putchar() works now, as does basexec03.bas. There are still some failing basexec tests though, notably the one with closures (which isn't too surprising but I'll try to look at it later).

**Comment by Wuerfel21** [comment]
> C function pointers are the same as Spin2 method pointers, and are handled in bytecode by the call_methodptr routine

Ah, the fat method pointer can be allocated statically? Huh. Idk my brain's kinda dense currently. Too much shrimp.

VBASE is pushed because `vbase_expr` is non-null for some reason. The dense fix would be to just ignore it if `indirect_call_expr` is set since that overrides VBASE anyways. But that's not right.

**Comment by Wuerfel21** [comment]
I think the problem may be higher up? `((f)->putcf)( (x), (f) )` is a call to a function pointer that is a member of a struct. Is it generating AST as if `f` is the call receiver? Again, brain density high right now.
