### ISSUE TITLE
Cool compiler crash with -O2 / loop-reduce

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#296]
```c
int main(int n) {
  int i;
  for(i=0; i<(n-1); i++) {}
}
```
Seems that the rhs of `i=0;` gets bungled somehow.

interestingly, this doesn't crash:
```c
int main(int n) {
  for(int i=0; i<(n-1); i++) {}
}
```

**Comment by totalspectrum** [comment]
Thanks, Ada. This is fixed now I think (there was a mess up when there were non-constant expressions in the limit).
