### ISSUE TITLE
nucode can't compile to high memory (-E -H)

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#297]
Seems like a reasonably simple fix...

(BC also can't, but it's got an excuse in that it needs that Spin startup header).
(Also, at some point the BC tests broke lmao. No idea what's going on there)

**Comment by totalspectrum** [comment]
The weird thing is that the BC tests work fine on my local machine, but on github there's some corruption in the output?

**Comment by Wuerfel21** [comment]
Local as-in real P1 or Spinsim on your machine?

**Comment by totalspectrum** [comment]
Spinsim on my machine. It looks like the real hardware works too, although I had to fix the test scripts that seem to have bit-rotted.

**Comment by totalspectrum** [comment]
It could be a race condition in spinsim; the error is some garbage being inserted in one string in the timing test (exec11).

**Comment by Wuerfel21** [comment]
Verified that CI compiles same binary that I get locally.

**Comment by Wuerfel21** [comment]
Update on the spinsim situation (should be its own issue, but oh well).
Apparently it receives an extraneous 0xFF byte (i.e. receiver state machine starting while line is idle). 
Still haven't found a vector for uncertainty.

**Comment by Wuerfel21** [comment]
So, copying a compiled spinsim exe from the CI onto a Mint 20.3 VM also doesn't fail the test. I already made sure that the test binaries are identical (well, the listings are the same, but they have all the bytes in them, so I hope the binaries are same, too)

**Comment by Wuerfel21** [comment]
Double-checked, exact same `exec11.binary`, exact same `spinsim` executable, no error.

Make it make sense.

**Comment by Wuerfel21** [comment]
Microcode bugs on M$ server CPUs???? :smiley:

**Comment by Wuerfel21** [comment]
Created new issue for that... issue

**Comment by totalspectrum** [comment]
I think this is fixed now, thanks for the bug report.
