### ISSUE TITLE
*.o needs depenency on `spin.tab.h`

### ISSUE THREAD

**Issue by DavidZemon** [totalspectrum/spin2cpp#3]
The makefile needs a dependency added on `spin.tab.h` so that it can be reliably run with parallel jobs. Specifically, line [78](https://github.com/totalspectrum/spin2cpp/blob/master/Makefile#L78). Without the dependency, it is possible to begin compiling some of the source code prior to spin.tab.h being generated.

**Comment by totalspectrum** [comment]
Thanks David. I've updated the Makefile and I think parallel builds should be reliable now (I tested with -j4). There's one quirk, which is that the job to build spin.tab.c and spin.tab.h runs twice; I'll try to fix that later, but it doesn't seem to cause any harm.

**Comment by DavidZemon** [comment]
Thanks. I've turned TeamCity back up to -j6 now that the change has been pulled into PropGCC :)
