### ISSUE TITLE
can't declare function aliases in a child object

### ISSUE THREAD

**Issue by avsa242** [totalspectrum/spin2cpp#301]
Hey there,

Going by the example in the spin docs,
```spin
PUB _add(x, y)
  return x+y
PUB add = _add
```
aliases seem to work fine in the top-level object, but declaring it in a child object fails to build:

top level:
```spin
obj

    ch: "child1"

pub main

    ch.add(1, 2)
```

child1.spin:
```spin
PUB _add(x, y)

    return x+y

PUB add = _add
```

```
Propeller Spin/PASM Compiler 'FlexSpin' (c) 2011-2022 Total Spectrum Software Inc.
Version 5.9.18-beta-v5.9.16-68-g29804a74 Compiled on: Oct 10 2022
ct.spin
|-child1.spin
error: can't find OBJ id for ch
ct.spin:7: error: request for member add in something not an object
ct.spin:7: error: add is not a member
Program size:      12 bytes
Variable size:      0 bytes
Stack/Free:     32740 bytes
```

I thought maybe it was some sort of collision with the `add` pasm instruction so tried a different name, but same result.
I'd originally seen this with 5.9.14, and updated to the latest just now to make sure it wasn't something that had been fixed, but also no change.

**Comment by totalspectrum** [comment]
I think this is fixed now in the github source code. Thanks for the bug report.
