### ISSUE TITLE
Local array initialization generates terrible code

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#311]
```c
void lmao() {
    int lol[100] = {0};
}
```
generates some 199 individual instructions. Should probably be some sort of memset/longfill call.

**Comment by Wuerfel21** [comment]
That's good for the generic case, but zero-fill should be memset because brr fast.

(Semi-relatedly, FlexC doesn't support empty initializer list `{}`. Used to be a C++ thing, but is also in C23 now)

**Comment by totalspectrum** [comment]
I think this is fixed now. If the initializer is all 0's then memset() gets used. An empty initializer list `{}` is treated the same as `{0}`.
