### ISSUE TITLE
Automating releases

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#317]
IIRC you said the reason not every point release gets a standalone CLI binary release is because it's a lot of effort for something that's not used very much.

It turns out it's possible to use github action scripting to automatically upload a release when a `vX.X.X` tag is pushed. Would just need to commit an evening to the exercise of patience that is debugging that stuff, which I'd only do if there's actual interest (for it causes me pain).

Main issues:
 - Currently there are two release zips. Is there any point to having the spin2cpp tool separate?
 - Currently the releases are Windows-only, which we already have a CI script for. Adding Linux support seems trivial, though glibc version stupidity might throw a wrench in that (maybe just static-link musl). I have no idea how to cross-compile for Mac OS. They do have an option for a native mac runner these days, [but due to the enormous weight of apple's corporate ego, the space-time around it is warped such that it consumes ten times the CI minutes that it would appear to from the outside](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#minute-multipliers).
 - Signing the binaries. The script that does it isn't actually committed to the repo... Github supports repository-scoped secret values, but these are text string only. Thus the certificate file needs to be base64'd to be conferred through the secret system (sounds jank, but [apparently that's just HowItsDone(tm)](https://docs.github.com/en/actions/security-guides/encrypted-secrets#storing-base64-binary-blobs-as-secrets)). Also there seem to be multiple possible formats for certificates, which one do you have?
 - What flags should they be built with?

**Comment by totalspectrum** [comment]
Hardly anyone downloads the spin2cpp / flexptools binaries; I see 9 downloads for flexptools.zip and 16 for spin2cpp.zip for the last release (5.9.16). So I'm not sure it's worth putting a lot of effort in. If it's something you're keen to do, I'd suggest just doing a Windows only release and not bothering with signing. Developers who want this stuff should understand and be able to work around warnings. Linux developers shouild certainly be able to build the tools themselves, but for Windows I guess it can be a pain to download and set up mingw for the build, so the CI products might be handy.

- If it's Windows only, probably no need to keep the zips separate (just have one with all the .exes and include files)
- I'd probably build with -O1 for release versions.

**Comment by Wuerfel21** [comment]
Yeah, signing probably is unnecessary hassle. I just mentioned it because the manual releases are signed and that may have some significance.

What might be neat would be to use NSIS or smth to generate an installer that automagically adds the install location to PATH, which I always think is mildly obnoxious to expect a general user to mess with, but is needed to properly use the compiler in scripts.

Also, I think if you just unzip the current release zips, the `include` dir isn't correctly found - I think the EXEs need to be moved into a subdirectory. Might fix that, too.

**Comment by Wuerfel21** [comment]
Interesting discovery: The CI builds as is have mildy curious version info because the CI clone is shallow and thus can't be adequately `git describe`d beyond the commit hash. I could set it to fetch the entire history, but that seems excessive. I guess that there are never more than 500 commits between tagged releases?
