### ISSUE TITLE
fastspin & spin2cpp fails to assemble local PASM labels for P2

### ISSUE THREAD

**Issue by dgately** [totalspectrum/spin2cpp#32]
Local labels in PASM code cause an error, when building for P2. When building Phil Pilgrim's PWMx8.spin for P2, with fastspin (& spin2cpp), the following errors display:
`$ fastspin -2 PWMx8.spin 
Propeller Spin/PASM Compiler 'FastSpin' (c) 2011-2018 Total Spectrum Software Inc.
Version 3.9.14-beta-1162b0d3 Compiled on: Jan  2 2019
PWMx8.spin
PWMx8.spin(140) error: syntax error, unexpected ':'
PWMx8.spin(146) error: syntax error, unexpected ':'
PWMx8.spin(155) error: syntax error, unexpected ':'
PWMx8.spin(158) error: syntax error, unexpected ':'
PWMx8.spin(163) error: syntax error, unexpected ':'
PWMx8.spin(178) error: syntax error, unexpected ':'
PWMx8.spin(180) error: syntax error, unexpected identifier `pwmbits'
PWMx8.spin(181) error: syntax error, unexpected ':'
PWMx8.spin(190) error: syntax error, unexpected ':'
PWMx8.spin(194) error: syntax error, unexpected ':
`
From the Propeller Manual v1.2:
> Local labels are similar to global separated from other same-named example:
> labels except they start with a colon ‘:’ and must be local labels by at least one global label.

[PWMx8.spin.zip](https://github.com/totalspectrum/spin2cpp/files/2741417/PWMx8.spin.zip)

Also note: the error on line 180, where pwmbits gets an unexpected identifier error. 

This code builds with fastspin & spinb2cpp for P1, without issue...

**Comment by drawkula** [comment]
For P1 inline assembler I had no liuck with "local labels" and had to rename them to have unique names in the whole source: http://yeti.freeshell.org/orgy/fastspin/fastspin.html#:flexspin:example:asm

Maybe that's related?

@totalspectrum ... are you planning to add local assembler lables?

**Comment by totalspectrum** [comment]
Local labels in P2 assembly are defined by starting them with a period ('.') rather than a colon (':') as in P1. That was Chip's decision, not mine, and I'll happily change it back if the official standard changes.
