### ISSUE TITLE
64-bit expression support broke Spin Hexagon again

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#329]
![Screenshot 2022-12-19 01-08-41](https://user-images.githubusercontent.com/6944842/208326752-310486d6-36ed-45f5-966f-5d93bf329d8a.png)

See this inexplicable player cursor on rendering on the title screen? This is the stuff. (In return, it's now missing during stage select)

After some bisecting, it turns out the sign of `constant( negx >> ((6-1)) )` changed because negx is now $FFFF_FFFF_8000_0000 and this causes the screen to flip along both axes.

I could fix this on my end, but it really seems like a bug to me.

**Comment by totalspectrum** [comment]
I think this should be fixed now (it probably worked with flexspin built with a 64 bit compiler before, but it works with both 32 and 64 bit compilers now).

**Comment by Wuerfel21** [comment]
Yep, fixed it! :+1:

**Comment by totalspectrum** [comment]
Thanks!
