### ISSUE TITLE
stest276 fails on my machine

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#331]
I should perhaps note that this always happens when I run the expect tests locally:
```diff
--- Expect/stest276.pasm        2022-12-19 01:19:49.513087100 +0100
+++ stest276.pasm       2022-12-19 02:50:26.655073900 +0100
@@ -22,6 +22,6 @@
        fit     496
        long
 _dat_
-       byte    $00, $00, $00, $80, $01, $00, $00, $00
+       byte    $00, $00, $00, $80, $00, $00, $00, $00
        org     COG_BSS_START
        fit     496
stest276 failed
```
Likely windows and/or 32-bit specific issue due to careless use of `long` or `intptr_t` somewhere, but I can't find it right now.

**Comment by totalspectrum** [comment]
I think this should be fixed now, there was a uintptr_t where there should have been a uint64_t.

**Comment by Wuerfel21** [comment]
I'd think it'd be a good idea to just get rid of all the intptr_t and long types. They brew trouble. I think intptr_t is used for Operand.val, which always seems like a hazard to me. Should probably be a union of void* and int32_t
