### ISSUE TITLE
Missing file-related definitions in libc.a

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#333]
In particular, missing are `feof` and also the `SEEK_SET` constants and friends.

**Comment by totalspectrum** [comment]
feof and ferror are in there now.

Symbols like SEEK_SET are defines, so really they don't belong in library (.a) files. I realize that it would be convenient to have them there for using libc.a as a Spin object, but I'm not quite sure that's the right use for .a files. There's some tension between wanting to keep them compatible with C usage and making them useful in other languages.

**Comment by Wuerfel21** [comment]
I don't think actual C even uses the libc.a, anyways?

Could just put them there as enum constants.

**Comment by totalspectrum** [comment]
I've added a file "libc.spin2", so now instead of:
```
OBJ c: "libc.a"
```
you just do
```
OBJ c: "libc"
```
The .spin2 version has the commonly used constants defined (we can easily add more).

**Comment by Wuerfel21** [comment]
Seems to work!

Also, somehow the NeoYume upcode got significantly smaller since the last build I had (6e5dec1d77b7b173e743f7af61132773eb7c4977), so take that win. (95796 byte to 88656 byte)

**Comment by totalspectrum** [comment]
Yay! I'll mark this one as "done" then.
