### ISSUE TITLE
Label-relative addressing is broken in inline ASM

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#334]
Works:
```spin
PUB main() | x
x := 1
org
.lbl    $+1,#0
        mov x,#2
end
```
Does not work (`error: Unknown symbol L__0003_01`):
```spin
PUB main() | x
x := 1
org
.lbl    mov .lbl+1,#0
        mov x,#2
end
```
(The label doesn't have to coincide with the instruction referencing it, that's just to keep the example terse)

**Comment by totalspectrum** [comment]
It's better now than it was. Inline asm will never be completely in sync with regular asm due to the weird way it is parsed :(
