### ISSUE TITLE
Fastspin segfaults when an enum used in a struct

### ISSUE THREAD

**Issue by hexaglow** [totalspectrum/spin2cpp#34]
Fastspin 3.9.23 segfaults when compiling a C file where an enum is used in a struct.

Code that triggers the segfault:

    enum SomeEnum { V1, V2 };

    struct SomeStruct {
      enum SomeEnum e;
    };

    int main(void) {}

Fastspin invoked as follows: `fastspin -2 -O2 bug.c` produces the following output

```
$ fastspin -2 -O2 bug.c
Propeller Spin/PASM Compiler 'FastSpin' (c) 2011-2019 Total Spectrum Software Inc.
Version 3.9.23 Compiled on: Mar 17 2019
bug.c
fish: “fastspin -2 -O2 bug.c” terminated by signal SIGSEGV (Address boundary error)
```

Fastspin was built with GCC 8.3.1 on Fedora 29

**Comment by totalspectrum** [comment]
Thanks for the bug report! I think this should be fixed now.
