### ISSUE TITLE
Improve stability of labels in generated assembly

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#340]
It'd really helpful for finding compiler bugs in larger programs if the generated labels weren't globally auto-numbered as they currently are. Creates a lot of diff noise.

**Comment by totalspectrum** [comment]
I've tweaked this a little bit in 6e5dec1d77b7b173e743f7af61132773eb7c4977 to reduce the number of diffs.

**Comment by Wuerfel21** [comment]
Thanks, works pretty well
