### ISSUE TITLE
NuCode: assigning a value to .byte[3] of a local FTBFS

### ISSUE THREAD

**Issue by avsa242** [totalspectrum/spin2cpp#341]
Hi Eric,

In the following snippet:

```spin
PUB my_method() | tmp

    tmp.byte[3] := 1
```

the build fails with the error `error: too many values in expression`

This only seems to affect spin2 NuCode.
The variable can also be one of the method's parameters, or the return value - still fails.
The assignment can be to `.word[1]` and that also fails.

Native code, as well as spin1 bytecode or native code build ok.
Any other value I tried for the byte number (e.g., `.byte[0]` thru ~~`.byte[3]`~~ `.byte[2]` as well as `.byte[4]`, or `.word[0]`) built ok also.
If the variable assigned to is a global, the build is also ok.

Cheers

**Comment by totalspectrum** [comment]
Thanks for the bug report! I think this should be fixed in the github sources now.
