### ISSUE TITLE
Symbols in child object's CON block not recognized when used as a default parameter value

### ISSUE THREAD

**Issue by avsa242** [totalspectrum/spin2cpp#342]
Morning! Got another strange one...

Consider this top object:
```spin
obj

    ch : "unknown-symbol-con"

pub main()

    ch.m1(1, 2)
```

and the child:

```spin
con

    ABC = %000

pub m1(a, b, c=ABC): s
```

FlexSpin (using 5.9.23)  produces an error about the `ABC` symbol (the naming doesn't seem to matter). The wording in the error is slightly different depending on the backend used, but same result:

NuCode:
```
unknown-symbol-con.spin2:5: error: identifier ABC not found
```

PASM2:
```
unknown-symbol-con.spin2:5: error: Unknown symbol ABC
```

and if the definition is __actually__ removed from the child object:
```
unknown-symbol-con.spin2:5: error: default parameter value must be constant
```

Using an integer as the default parameter value works, though (e.g., `1` in place of `ABC`)
Optimization seems to have no effect.
I'm not sure how I've never run into this lol... I went as far back as flexspin 5.9.10 and it still bombs. I thought for sure I've been using this feature somewhere for a long time, and indeed in my `com.i2c.spin2` I2C engine, I use it as a default for the bus speed parameter. That's generally used as _grandchild_ object, so not sure if that makes a difference, but it builds fine. I haven't yet distilled that one down to something I could reproduce the build failure with though.

**Comment by avsa242** [comment]
Hmmm...not sure if it's related, but using two CON symbols as a case in a `case` block doesn't match the case.
e.g.,
```spin
con

    BS = 8
    DEL = 127

pub char(ch)
    case something
        BS, DEL:
            'do something
```

No errors, the case just doesn't match. Haven't verified this as a standalone example like above, so maybe it needs more supporting code to reproduce.

**Comment by avsa242** [comment]
Okay nope, disregard that 2nd issue...was due to an uninitialized variable.

**Comment by totalspectrum** [comment]
Thanks for the bug report. This should be fixed in the github sources now.
