### ISSUE TITLE
P1 BC (spin2): Crash depending on where an array (VAR) is positioned

### ISSUE THREAD

**Issue by avsa242** [totalspectrum/spin2cpp#344]
Hi guys,

This one had me chasing my tail for a bit...
In this spin2 code:

```spin
CON

    _clkmode    = xtal1+pll16x
    _xinfreq    = 5_000_000

OBJ

    ser : "fullduplexserial"

VAR

    long array1[50]
'    long array2[50]                            ' works with this definition
    word word1

PUB main()

    ser.start(31, 30, 0, 115_200)
    waitcnt(cnt+clkfreq/10)
    ser.str(@"Serial terminal started")         ' watch for text corruption on this line

    cognew(cog_two(), @array2)

    repeat

VAR long array2[50]                             ' crashes with this definition
PUB cog_two()

    repeat
```
There is a bit of visible corruption on the serial terminal when the secondary cog is started.
Command line used is `flexspin -1 --interp=rom crash1.spin2`

If the second definition of `array2` is commented out and replaced with the first, all is well (or appears to be in this simple snippet).
If the snippet is saved to a file with a `.spin` extension, all is well (same note).
If the `word1` definition is commented out, all is well.
If compiled instead of bytecode, all is well.
Increasing the stack space affects the behavior, but doesn't fix the crash (e.g., increase the second definition to 500 longs: it'll _appear_ to be okay now. But add another long definition right after the first array and the corruption is visible again.)

I went as far back as maybe a few commits past when P1 bytecode support was first added a couple years ago and it was the same issue. Have I just made an error coding it that way (alignment issue in memory?) or do you think this is a genuine bug? I don't have any issue with relocating the definition to the top spot if it's my error - in my original code that triggered this, I just put the VAR definition right next to the `cog_two()` to serve as a visual indicator that the array was only used there.

Thanks!

**Comment by Wuerfel21** [comment]
Does the issue still happen if you put an `alignl` line before the array definition? Spin2 structure layout is different and doesn't automatically align and unaligned stack may cause the cog booter to trip balls, idk. Just a guess. Though in that case the ASM code would also be subtly broken...

There isn't a lot of VAR section code in the backends, so probably yes. IIRC all the layout stuff happens in the frontend and the BC backend just pulls member offsets and the total size of the top object.

**Comment by Wuerfel21** [comment]
Turns out yes, the cog runner would get tripped by unaligned stack pointer : https://github.com/parallaxinc/Propeller_1_Design/blob/master/runner.src

**Comment by avsa242** [comment]
Just tried modifying it as in:

```spin
VAR

    alignl
    long array2[50]                             ' crashes with this definition
PUB cog_two()

    repeat
```

with the same result.

**Comment by Wuerfel21** [comment]
Okay, checked it locally.

- It is the suspected alignment issue.
- ASM backend is also broken, you just can't tell in this contrived example because coginit is a bit simpler for ASM.
- ALIGNL directive is busted

**Comment by Wuerfel21** [comment]
```
'--- Function main
0020: 01                      ' ANCHOR  (DISCARD)
0021: 38 1F                   ' CONSTANT 31
0023: 38 1E                   ' CONSTANT 30
0025: 35                      ' CONSTANT 0
0026: 3A 01 C2 00             ' CONSTANT 115200
002A: 06 03 01                ' CALL_OTHER 3.1 (ser.Start)
002D: 3F 91                   ' REG_READ 1F1(CNT)
002F: 35                      ' CONSTANT 0
0030: C0                      ' MEM_READ LONG (POP base) 
0031: 38 0A                   ' CONSTANT 10
0033: F6                      ' MATHOP: DIVIDE
0034: EC                      ' MATHOP: ADD
0035: 23                      ' WAITCNT
0036: 01                      ' ANCHOR  (DISCARD)
0037: 87 3B                   ' FUNDATA_PUSHADDRESS +59 +PBASE
0039: 06 03 06                ' CALL_OTHER 3.6 (ser.Str)
003C: 38 02                   ' CONSTANT 2
003E: CB 80 CA                ' MEM_ADDRESS LONG VBASE+$00CA    <------- VERY COOL UNALIGNED OFFSET
0041: 15                      ' COGINIT_PREPARE
0042: 34                      ' CONSTANT -1
0043: 3F 8F                   ' REG_READ 1EF(DCURR)
0045: 37 61                   ' CONSTANT -4
0047: D1                      ' MEM_WRITE LONG (POP base)+(POP index) 
0048: 2C                      ' COGINIT
```

**Comment by Wuerfel21** [comment]
So I guess align directives need fixing and there needs to be a disclaimer about memory alignment when using Spin2 on P1.

**Comment by avsa242** [comment]
Ahhh okay, I wondered if I wasn't actually hitting it or if the example was too simple to show it - probably should've just tried to build my original code that triggered it.

**Comment by totalspectrum** [comment]
There were two bugs:
(1) ALIGNL was being overridden by the second pass of variable offset fixups
(2) Spin2 variables were not being aligned by default on P1

I think both of these should be fixed in the source code now. Thanks for looking into this Jesse and Ada.
