### ISSUE TITLE
Regression: warning for missing # is busted

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#347]
```
DAT

              org
              shl pa,1
```
doesn't generate a warning anymore on current version. Haven't done a bisect, but of the versions I have binaries laying around for, da3db2508e9fe867cab2150c8a63f3c1847a14bf is the newest that still works.

**Comment by Wuerfel21** [comment]
Bisected to f905169e145d6b66ae8038508eb13eb3d55d6012

**Comment by totalspectrum** [comment]
Thank you, I've checked in a fix for this (and for some other warning problems).
