### ISSUE TITLE
Bug or design decision? Object's OBJ name doesn't default to .spin2 extension when containing file is .spin2

### ISSUE THREAD

**Issue by PropGit** [totalspectrum/spin2cpp#35]
Even though an object's filename includes a .spin2 extension, if it's containing OBJ block doesn't specify a child object's extension as .spin2, fastspin appends .spin, and subsequently can't find the child object in the filesystem (if it had a .spin2 extension, of course).

Found this while compiling [PauseDemo.spin2](https://github.com/parallaxinc/propeller/blob/master/examples/EZLib/PauseDemo.spin2).

**Comment by totalspectrum** [comment]
Thanks for the bug report. This was a design decision, but a poor one. In the next version of the compiler it will always try to look for a .spin2 files first, then a .spin file, if no explicit extension is given.
