### ISSUE TITLE
Revert Spin2 loop value behaviour

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#356]
PNut v38 is going to revert to change, so might as well.
![image](https://user-images.githubusercontent.com/6944842/215301271-abcd9ebb-9a4b-4c53-afed-eedb156299be.png)

(Probably a good excuse to increment the minor version to 10)

**Comment by totalspectrum** [comment]
This has been reverted, and the version number will be bumped to 6.0.0 once things have settled down.
