### ISSUE TITLE
frequent explicit orgh warnings

### ISSUE THREAD

**Issue by PropGit** [totalspectrum/spin2cpp#36]
Every Spin2 program seems to result in the same warnings:
```
warning: orgh with explicit origin does not work if Spin methods are present
```

**Comment by totalspectrum** [comment]
This is a problem with creating listing files (it only happens if the listing window is open). It's fixed in github now and will be in the next release.

Thanks for the bug report!

**Comment by PropGit** [comment]
You're welcome!  Confirmed.
