### ISSUE TITLE
Conditional assembly broke IF DEBUG expressions

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#368]
```spin
DAT
              org
              debug(if(1),"lol")
```
oh no were broke.

**Comment by Wuerfel21** [comment]
Appears to be fixed at 39eae6185dcaa3f97a8ab96fd0f961aa976df9d8

(funny trick: If you put something like "Fixes #368" or "Closes #368" into your commit message, it auto-closes the issue with a link to the commit)

**Comment by totalspectrum** [comment]
Thanks, that's a useful tip.
