### ISSUE TITLE
Error: Request for member...

### ISSUE THREAD

**Issue by PropGit** [totalspectrum/spin2cpp#37]
Here's an example where fastspin fails to compile an existing Spin application.

It appears to fail on an object constant reference: ```pst#CS```

~~~
Propeller Spin/PASM Compiler 'FastSpin' (c) 2011-2019 Total Spectrum Software Inc.
Version 3.9.23 Compiled on: Mar 16 2019
StackLengthDemoModified.spin
|-Stack Length.spin
|-|-Parallax Serial Terminal.spin
C:/Temp/_propeller_experiments/fastspin/Library/Stack Length.spin(70) error: request for member cs in something not an object
C:/Temp/_propeller_experiments/fastspin/Library/Stack Length.spin(70) error: request for member cs in something not an object
~~~

Here's an archive of the files involved:
[StackLengthDemoModified - Archive  [Date 2019.03.22  Time 13.52].zip](https://github.com/totalspectrum/spin2cpp/files/2998297/StackLengthDemoModified.-.Archive.Date.2019.03.22.Time.13.52.zip)

**Comment by totalspectrum** [comment]
That was an interesting bug -- if a sub-object referred to constants in a different sub-object it didn't work properly. It should be fixed now though. Thanks for reporting this!

**Comment by PropGit** [comment]
You're welcome.  Confirmed.
