### ISSUE TITLE
#A operand encoding difference when jumping between Cog and LUT memory

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#370]
```spin
DAT
        org 0
label1
        jmp #label2
        org $200
label2
        jmp #label1
```
Proptool assembles as: `FC 07 90 FD  FC F7 9F FD` (relative mode? but _weird?_)
flexspin assembles as: `00 02 80 FD  00 00 80 FD` (absolute mode)

**Comment by totalspectrum** [comment]
This should be fixed now.
