### ISSUE TITLE
P2 sometimes generates shift/add sequence instead of MUL/MULS

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#374]
IIRC this has something to do with the type check for MUL(S) vs. QMUL being done later than the shift optimization check.

**Comment by totalspectrum** [comment]
Do you have an example for this? The simple test case I used to try to reproduce it doesn't do this:
```
unsigned prod(unsigned short a) {
    return a * 2;
}
```
generates
```
_prod
        mul     arg01, #2
        mov     result1, arg01
_prod_ret
        ret
```

**Comment by Wuerfel21** [comment]
I may have had a brainfart in that moment. I think the issue was that it got type-promoted and thus didn't use MULS
