### ISSUE TITLE
REP in inline ASM breaks local-reuse

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#376]
Using REP in inline ASM breaks local-reuse because manually placed REPs do not generate `OPC_REPEAT_END` IRs, which can registers to appear dead even if they aren't.

Not sure what the ideal way to fix this is. For simple cases just inserting the end marker should suffice. But we can't always really do that, so maybe auto-disable local-reuse pass in these cases? A stupid solution would be to disable it around volatile instrs, but that's bad, since aliasing user temps and compiler temps around inline ASM is one of the things it's supposed to help with.

Example:
```c

void main() {
    int x = 0,y;
    __asm volatile {
        rep @.test1,#5
        add x,#1
        wrlong x,#0
        rdlong y,#0
        wrlong y,#0
    .test1
    }
}

```

**Comment by totalspectrum** [comment]
Actually I think disabling register re-use for volatile instructions is the right thing to do -- volatile means volatile, we really don't want to surprise the user with any changes to the assembly. This doesn't fix all the cases, but it at least provides a work-around (and fixes the specific case you show above).

**Comment by Wuerfel21** [comment]
I disagree. The particular identity of any local register is assigned semi-randomly anyways. For the few clever cases where it would cause issues (assuming the majority of REP cases would be fixed), I don't think manually disabling it is a downside.

**Comment by totalspectrum** [comment]
I've kind of punted by adding a warning about REP in non-volatile assembly and marking it volatile. For now the "no register re-use accross volatile" remains, because I actually think that's less likely to lead to surprises.

**Comment by Wuerfel21** [comment]
The way you've done it I think is ok. You're only ignoring dependency chains that _start_ on a volatile op, which I think(?) still allows certain re-use scenarios. A bit scatterbrained today, so the full implications aren't 100% clear to me right now. Anyways, the logical bugs in my code are fixed, so that's something.
