### ISSUE TITLE
__fromfile name mangling issue

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#377]
When I declare a fromfile function in C like
```c
static void block_idct (
	int32_t* src,	/* Input block data (de-quantized and pre-scaled for Arai Algorithm) */
	jd_yuv_t* dst	/* Pointer to the destination to store the block as byte array */
) __fromfile("fast_idct.spin2");
```
the definition in the referenced file has to have a semi-random number attached to be found:
```spin
PUB block_idct_0055(src,dst) | v[8], b[4], t10, t11, t12, t13, t20, t21, t22, t23, m13c
```

**Comment by totalspectrum** [comment]
Actually static isn't compatible with __fromfile at all, and there should be an error if they are mixed (the function is coming from another file, so it can't be static).

**Comment by Wuerfel21** [comment]
Oh well, didn't notice it was static :)

I think the reason I actually did this was not being able to get some inline asm skullduggery to work in C. Should investigate and report that one!
