### ISSUE TITLE
C local arrays can't be used in inline ASM

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#382]
```c
void main() {
    int lmao[4];
    __asm volatile {
        mov lmao+1,lmao+0
    };
}
```
Causes great sadness: `arrayasm.c:3: error: Variable lmao must be placed in memory (probably due to an @ expression) and hence cannot be accessed in inline assembly`

**Comment by totalspectrum** [comment]
This is a "feature", C arrays always go in hub memory. If you really need to you can use a struct to get around this, or just declare registers in the inline assembly.

**Comment by Wuerfel21** [comment]
Structs don't work either, I am pretty sure I tried. I can RES variables in inline ASM though? Never seen that.

**Comment by Wuerfel21** [comment]
No, RES doesn't work either:
![image](https://user-images.githubusercontent.com/6944842/235350089-dc905915-2a74-41d9-97f8-4301120440b8.png)

**Comment by Wuerfel21** [comment]
Maybe just make the `register` qualifier give the spin-like behaviour?

**Comment by totalspectrum** [comment]
RES may not work, but LONG should.

**Comment by Wuerfel21** [comment]
but LONG bloats up the size of the fcache load

**Comment by totalspectrum** [comment]
Structs are placed into registers for up to 12 bytes; I think they were intended to work up to 16 bytes, not sure why they're not. You can also use pr0...pr7 for up to 32 bytes, or declare variables as long. The Spin2 arrays in registers are really fragile and hacky, and I don't want to import that hackiness into C (particularly when it comes to arrays of things smaller than a register) so  sorry, this is a "won't fix".
