### ISSUE TITLE
Can't constant override with constant from parent object

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#385]
Something like this
```spin
CON
LMAO = 1

OBJ
b : "bottom" | AAAA = LMAO
PUB main()
```
yields a `top.spin2:4: error: new value for AAAA is not constant`. I think this is because the expression is eval'd in the context of the sub-object, since its constants _can_ be used. Proptool actually doesn't allow that... (seemingly at all, which is irritating)

**Comment by totalspectrum** [comment]
Should be fixed now.

**Comment by Wuerfel21** [comment]
Cool, but now you can't use constants from inside the object. (For example, in the USB driver thing, I have constants for all the keyboard scancodes that I want to use for configuring pad emulation)

**Comment by totalspectrum** [comment]
You mean "you can't use constants from inside the object" on the object override itself? You shouldn't expect to be able to use constants from inside the object in the parent's context, at least not without qualifier. You *can* do something like:
```
' top.spin2
CON
  LMAO=200

OBJ
  b1 = "bottom" ' dummy object, not instantiated
  b: "bottom" | AAA = b1.CCC

PUB main()
  OUTA := b.foo()
```
with
```
' bottom.spin2
CON
  AAA = 9
  BBB = AAA + 4
  CCC = 1000
  
PUB foo() : r
  r := BBB
```

**Comment by totalspectrum** [comment]
I don't see an unambigous way to allow constants from inside the object to override values (while at the same time allowing the parent's symbols to be used as well), but I'm open to suggestions. I like the explicit "b.X" syntax because it makes it clear where the symbol is coming from.

**Comment by Wuerfel21** [comment]
`b.X` would be totally ok. By "silly" I mean having to create a dummy `b1` to pull the constants from.

**Comment by totalspectrum** [comment]
Ah, I see. That one's kind of a chicken and egg problem. We're in the process of defining b (and its constants) so we can't really use constants from b itself, i.e. b.CCC isn't defined yet in the parent because "b" isn't :(.
