### ISSUE TITLE
Seemingly unused BASIC I/O adapter functions included in build

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#393]
While admiring the new alloc-free function pointers I noticed that there are spurious `__struct___bas_wrap_sender_tx`, `__struct___bas_wrap_sender_rx` and `__struct___bas_wrap_sender_close` functions included into the binary when building NeoYume's upcode. This also happens in older versions (where it's clearer that they really are never referenced). It seems these are member functions of a structure only used in `_basic_open`, which is not present in the binary.

Maybe also emit comments or something when generating a method pointer create sequence so it's clear what method is being pointed to.

**Comment by Wuerfel21** [comment]
I tried to fix this by moving everything basic-related out of fmt.c and while that fixed the issue and removed 5 unused-but-included functions, it breaks the basic exec test in ways so bizarre I don't even want to try to understand.
![image](https://github.com/totalspectrum/spin2cpp/assets/6944842/e8af960d-4257-4b22-90c0-84b5ffed5116)





Can you please look into either doing that properly or fixing the actual issue that keeps these functions from being removed?

**Comment by totalspectrum** [comment]
This should be better now, at least for NeoYume.

**Comment by Wuerfel21** [comment]
Fix works :+1: 

Relatedly, I see you added argv support to flexc/loadp2?

- Have you actually tested that loadp2's implementation works with my stuff (can't test right now due to running some stability test I don't want to reset)
- The code isn't guarded for P2 only. Reading FC000 is safe for P1 because in ROM, but it isn't useful. Would have to figure out a sensible convention for P1. I think Catalyst has one that's vaguely sensible (i.e. still allows a full 32K binary)

**Comment by totalspectrum** [comment]
I'm not actually in a position to run NeoYume right now (it compiles just fine though :)). I *think* the loadp2 ARGv code should be compatible with it, that's certainly the intention.

This raises another issue though, which is that -gbrk debugging uses $FC000 and so ARGv and gbrk aren't compatible :(. Would moving to another address make sense? Although I'm not sure what memory is safe from the debugger;  I tried experimenting with FE000 and FF000 but had no luck.

**Comment by Wuerfel21** [comment]
No EC32MB? (insert the megamind image here)

The address conflict is somewhat intentional. The debug/boot area is somewhat guaranteed to not be used by the actual user program. (Also, I don't think all/any(?) of the usual load methods don't clear unused memory, so the boot area getting nuked on reset also prevents lingering args) When debugging a program, it should be possible for you to hardcode any parameters.

Though I don't think anything actually prevents using debug and ARGv together. The hardcoded CPU state dumping happens up at FFxxx. So the debugger startup could be modified to make args end up in the right place.

**Comment by Wuerfel21** [comment]
Though that wouldn't work if app+debugger are larger than 496k, at least with the current blob prepend method. Could be made to work by loading the debugger directly to high memory.
