### ISSUE TITLE
error: Internal Error: emitting move to immediate

### ISSUE THREAD

**Issue by avsa242** [totalspectrum/spin2cpp#40]
Hi Eric,

When building the attached (top-level object is LEDMatrix1.spin2), fastspin aborts with the subject error. Bisecting finds this issue was introduced in 33caf969bca5155668ae65e0eb197b78045da743

I find that a workaround is to change line 209 of display.gfx.bitmap.spin2 from -1 to TRUE, and the source builds successfully.

Any ideas if this is a bug or a feature? :)

Thanks!
Jesse
[LEDMatrix1.zip](https://github.com/totalspectrum/spin2cpp/files/3294309/LEDMatrix1.zip)

**Comment by totalspectrum** [comment]
That's definitely a bug. Thanks for catching this. It should be fixed in 47117a.
