### ISSUE TITLE
Unitialized bedata error in BC when using certain expressions

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#405]
```spin
PUB main()

DAT
a
b
long 0[@a-@b]
```

```
bad-bedata.spin:6: error: BCgetDAToffset: bedata for module Bad_bedata uninitialized
bad-bedata.spin:6: error: BCgetDAToffset: bedata for module Bad_bedata uninitialized
```

Something trying to resolve data size before the backend is ready?

**Comment by totalspectrum** [comment]
The expression evaluator was trying to fully evaluate the addresses @a and @b to find how big the DAT section needs to be, which is before the backend is ready. In this particular case though we don't need accurate addresses, just relative ones. I've checked in a fix for this, thanks.
