### ISSUE TITLE
No CASEs match

### ISSUE THREAD

**Issue by avsa242** [totalspectrum/spin2cpp#41]
Hi Eric,

In the attached code, I'm calling the Line method with the 'c' parameter set to -1, but the case inside never seems to match. If I place some debugging code inside the method to print the value of c out to the display/terminal before the case block is evaluated, it shows c indeed equals -1. If I place that same debug code _inside_ the -1 case, it never executes. If I comment out the case block completely, and just paste the code from the -1 case, the code executes properly. If I replace the case block with if..elseif (commented out therein), the code also executes.

Thanks!

[display.gfx.bitmap.spin2.zip](https://github.com/totalspectrum/spin2cpp/files/3308174/display.gfx.bitmap.spin2.zip)

**Comment by totalspectrum** [comment]
Thanks Jesse! That's a really nasty bug -- actually there were two problems, the code for figuring out when to use jump tables and when to use if/then/else was backwards, and then the if/then/else code was also getting corrupted by adjustments that were needed for the jump tables.

Thank you for the bug report. It should be fixed now, but please re-open this if the current github doesn't work right for you.
