### ISSUE TITLE
Project with child obj containing obj pointer and array of its own child objects FTBFS

### ISSUE THREAD

**Issue by avsa242** [totalspectrum/spin2cpp#411]
Stumped with this one...can't tell if I'm just not seeing something dumb I'm doing or if this is a genuine bug...

```spin
' top.spin
obj

    child: "child"
    child2: "child2"

pub main()

    child.main(@child2)
```

```spin
' child.spin:
obj

    sibling=    "child2"
    child[2]: "grandchild"

pub main(ptr): r

    child[0].main()
    r := sibling[ptr].main(4)
```

```spin
'child2.spin:
pub main(a): c | b

    b := 16
    c := b*a
```

```spin
'grandchild.spin:
var

    byte _var


pub main()

    _var := 1

```

`top.spin` fails to build with:
```
Version 6.3.0 Compiled on: Aug 15 2023
top.spin
|-child.spin
|-|-child2.spin
|-|-grandchild.spin
|-child2.spin
/home/avsa242/prop/github/bugs/obj-arrays-compile-err/child.spin:4: error: Not an identifier
/home/avsa242/prop/github/bugs/obj-arrays-compile-err/child.spin:4: error: Not an identifier
/home/avsa242/prop/github/bugs/obj-arrays-compile-err/child.spin:4: error: Expected identifier
/home/avsa242/prop/github/bugs/obj-arrays-compile-err/child.spin:8: error: request for member main in something not an object
/home/avsa242/prop/github/bugs/obj-arrays-compile-err/child.spin:8: error: main is not a member
Program size:      88 bytes
Variable size:      8 bytes
Stack/Free:     32656 bytes
```

I went way back to FlexSpins of mid-2021 vintage and they had the same issue, so it's nothing that was changed recently...
If you remove either the call `r := sibling[ptr].main(4)` from child.spin or the declaration of `child[2]: "grandchild"` (and the call to its method), the build succeeds, but both can't be present. Any ideas?

**Comment by totalspectrum** [comment]
This seems only to be an issue with the P1 bytecode backend (-1bc). I'll look into it, I suspect it's related to the tangled attempt to derive types in the memory access code.

**Comment by totalspectrum** [comment]
I fixed it so it compiles now; I'm not sure if the generated code is correct though, that still needs more investigation.

**Comment by avsa242** [comment]
This only expands (or hopefully makes a bit clearer) the original contrived example I attached, but attached is an updated archive that tests the fix. It _does_ indeed seem to work, at least in this case. I suppose top.spin could be made more dynamic - maybe a loop that fills `x` number of grandchildren with some known values, and then reads them back to compare them, but this at least tests the basic functionality.

[obj-arrays-compile-err-fixed1.zip](https://github.com/totalspectrum/spin2cpp/files/12388486/obj-arrays-compile-err-fixed1.zip)

**Comment by totalspectrum** [comment]
Thanks! Sounds like this bug is resolved then.
