### ISSUE TITLE
VFS inconsistency: LittleFS directory listing returns . and .. directories, FAT doesn't

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#412]

**Comment by totalspectrum** [comment]
This is a feature of the underlying file systems. FAT has . and .. directories only in subdirectories (not in the top level directory), whereas LittleFS has them in all directories. The VFS layer is just passing on what the information on disk looks like.

**Comment by Wuerfel21** [comment]
I'm pretty sure that isn't quite what it is. I just tried to run megayume and its funny little file chooser off of LittleFS. That has . and .. directory entries showing (in addition to the actual up entry that I add), which never happens with FAT. I don't have a special case for these, so evidently the FAT VFS doesn't return them.

(Also, it seems can't get large (7M+) files onto it. Just ends up with 0 bytes after the copy. Yes I changed the used area to be larger than the default. Also, the RAM usage is outrageous...)

**Comment by totalspectrum** [comment]
Hmmm, interesting... FATFS explicitly skips over the . and .. entries that are on disk. So does the 9p file system. I'll remove the littlefs code that handles . and ..; I'm a little reluctant to mess with the filesystem code (which is ugly and huge) but those particular cases seem to be hacked in anyway, so it doesn't look too bad.
