### ISSUE TITLE
No error for instructions with impossible flags when compiling Spin files with unused DAT section

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#414]
Certain instruction/flag combinations are impossible (such as `BITL D,S WC` or `BITL D,S WZ` or `GETBRK D '(no flags)`, but flexspin doesn't error out when trying to assemble these.

**Comment by totalspectrum** [comment]
The `getbrk d` one I can reproduce (and it's easy to at least add a warning for this). `bitl pa, pob wc` gives me an `error: modifier wc not valid for bitl`.

**Comment by Wuerfel21** [comment]
Remember, I'm an idiot, so there's a large possibility I messed up the testing

**Comment by Wuerfel21** [comment]
Though I think I can pull out a list of instructions with funny flags, so I guess I'll go back and test them all

**Comment by Wuerfel21** [comment]
Turns out I'm not stupid, I just tested it in a file with a spin main function. Unreferenced DAT sections are never compiled, etc, etc.

Probably not-a-bug.

**Comment by Wuerfel21** [comment]
But GETBRK without flags should be an error because that encodes COGBRK.

**Comment by totalspectrum** [comment]
I've changed the missing wcz on GETBRK from a warning to an error, and did the same to modcz.

**Comment by Wuerfel21** [comment]
MODCZ you can actually encode without C/Z flags (completely pointless, but whatever...)

Another one: You can't have WMLONG with an immediate D, that also doesn't error.
