### ISSUE TITLE
Function missing from ASM output

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#425]
[ranquest-2024-01-17.zip](https://github.com/totalspectrum/spin2cpp/files/13968965/ranquest-2024-01-17.zip)

Compile as `flexspin -2 ranquest.spin`, beget `ranquest.p2asm:6378: error: Unknown symbol '_compat_video_wrapper_set_border'`. Happens on slightly old build as well, so not related to recent changes. Haven't tried building this in ages.

**Comment by totalspectrum** [comment]
Thanks for the bug report, it should be fixed now (odd case of a function being inlined in most places, but not in a different object).
