### ISSUE TITLE
include/libc.a

### ISSUE THREAD

**Issue by dbetz** [totalspectrum/spin2cpp#44]
Is there a reason that libc.a is checked into the spin2cpp/include directory?

**Comment by totalspectrum** [comment]
Yes,  the include directory is searched automatically for files and that's convenient for something like libc.a.

If you look at it you'll see it's just a text file (so it is literally an include file right now).

It's checked in because I don't yet have a convenient way to regenerate it.

**Comment by dbetz** [comment]
I wasn't so much asking why it ended up in the include directory. I was just wondering why a binary file was checked into GitHub. Shouldn't it be built from sources that are checked in?

**Comment by dbetz** [comment]
Never mind. I see it isn't really a binary file.
