### ISSUE TITLE
P2: Can't assemble branches with long immediates

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#444]
```
DAT
              org
              tjnz pa,##.label
              long 0[400]
.label        jmp #$
```
I'm fairly sure this should work.

Also, I think I saw a really stupid workaround for this issue somewhere in assemble_ir.c

**Comment by totalspectrum** [comment]
This should be fixed now. One quirk of this instruction encoding is that PNut, at least, only encodes 18 bits for the signed offset in the AUGD + tjnz, rather than the full 32 bits that are available. I've made flexspin do the same.
