### ISSUE TITLE
Abstract objects don't work anymore

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#445]
I often use abstract objects when I just want to access constants from an object.

Now I get this crap: `config.spin2:58: error: syntax error, unexpected '.', expecting '['`
(the dot being the constant access on the abstract object)

I bisected breakage to commit e6b1d1e8425b6041731b0c0b0f1a4346b3138ea4

**Comment by totalspectrum** [comment]
That should be fixed now. I didn't actually intend abstract objects to be usable that way, but it does seem useful. I've also made it possible to access static data (the DAT section) of abstract objects, since that is shared with all concrete objects.

**Comment by Wuerfel21** [comment]
Fix isn't pushed

**Comment by totalspectrum** [comment]
Ah, the joys of git. It's pushed now. Thanks for checking!
