### ISSUE TITLE
constants not recognized in structure definitions

### ISSUE THREAD

**Issue by avsa242** [totalspectrum/spin2cpp#457]
When defining a structure, CON symbols don't seem to be picked up before the pass that processes structure definitions, so doing something like defining a member as an array with a size defined by a CON generate an error while building.

e.g.:
```spin
con

    ARRAY_SZ = 256                              { not picked up by the struct def below }
'#define ARRAY_SZ 256                           { this works OK }

    somestruct( byte somearray[ARRAY_SZ] )
```

generates the error:
```
Propeller Spin/PASM Compiler 'FlexSpin' (c) 2011-2024 Total Spectrum Software Inc. and contributors
Version 7.0.0-beta2-v6.9.7-98-gbc23bf43 Compiled on: Nov 24 2024
cons_not_recognized_in_struct_defs.spin2
cons_not_recognized_in_struct_defs.spin2:6: error: Unable to determine size of array
cons_not_recognized_in_struct_defs.spin2:6: error: Unable to determine size of array

shell returned 1
```

As a workaround, a preprocessor define works in its place.
spin1, spin2, both nu/bytecode and pasm backends all generate the same error

Cheers!

**Comment by totalspectrum** [comment]
This is an unfortunate side effect of the way structures are implemented as objects. I guess they'll have to import their parent's constants. I'll look into this, and thanks for the bug report.

**Comment by totalspectrum** [comment]
I *think* there's a fairly simple fix for this, and it should work correctly now in github.

**Comment by avsa242** [comment]
Confirmed, this seems to work, thanks!

**Comment by totalspectrum** [comment]
@avsa242 Thanks for reporting this and for letting me know it's fixed!
