### ISSUE TITLE
spin: return value not passed if inline expression given

### ISSUE THREAD

**Issue by avsa242** [totalspectrum/spin2cpp#46]
Hi Eric @totalspectrum 
I'm finding `return` behaves a little differently using fastspin vs openspin.
In my method below:
```
PUB AutoRetransmitCount(tries) | tmp
' Setup of automatic retransmission - Auto Retransmit Count
' Defines number of attempts to re-transmit on fail of Auto-Acknowledge
'   Valid values: 0..15 (0 disables re-transmit)
'   Any other value polls the chip and returns the current setting
    readReg (core#NRF24_SETUP_RETR, 1, @tmp)
    case tries
        0..15:
        OTHER:
'            return (tmp & core#BITS_ARC)    ' <- Using return with an inline expression returns 0 (yields expected return value using OpenSpin)
            result := (tmp & core#BITS_ARC)  ' Pre-defining result and returning on the next line yields the expected return value
            return
    tmp &= core#MASK_ARC
    tmp := (tmp | tries) & core#NRF24_SETUP_RETR_MASK
    writeReg (core#NRF24_SETUP_RETR, 1, @tmp)

```
in the ```OTHER``` case, if I attempt to return an expression, nothing is returned, but if I pre-define a variable with the expression, and return that variable (or just ```return```, if the variable is defined as the return var in the method definition line), the expected value is returned.
Is this expected behavior or do you think it's a bug? It's dead simple to work around, either way.
This is in a child object, in case it's significant. EDIT: Also, this is spin2 on a P2.

Thanks!
Jesse

**Comment by totalspectrum** [comment]
Return values should work, but there was a bug in Spin case statements in some versions of fastspin. Does your code work correctly in fastspin 4.0.2? The generated code in that version seems to be OK when I look at it.

Thanks,
Eric

**Comment by avsa242** [comment]
Looks like it behaves the same way in 4.0.2. After trying one more commit a few older (I think it was the one tagged 4.0.1), I decided to try bisecting it out, instead. Looks like it started with 33caf969bca5155668ae65e0eb197b78045da743

`added CASE_FAST for spin, and implemented jump tables for case/select/switch`

Hadn't thought of trying it before, so I tried `case_fast` instead, and it returns the correct value.

**Comment by totalspectrum** [comment]
Ah, that certainly gives some more information, thank you. However, I'm still having trouble reproducing this. Could you clarify, is it in the OTHER case or in the 0..15 case that the unexpected return value happens? There's no return value defined for the case 0..15 in fastspin. In openspin this may default to having a return value of 0, so that is a difference between the two.

If you add "return 0" to the end of your function does that change anything?

**Comment by avsa242** [comment]
Yes sorry, it's in the OTHER case. In the snippet above, I intentionally let it "fall through" the case block if the number is in a valid range (0..15), since in that example, no special processing is needed if that particular case matches.

Wow...okay, I didn't expect that...Yes it changes: I added a `return 0` to the end of the method (despite the OTHER case having a return statement that matches) and the OTHER: case now returns the expected value.

If I pare the code down to this, just for the purposes of testing:

```
PUB MyMethod(tries) | tmp

    tmp := 3
    case tries
        0..15:
        OTHER:
            return (tmp & %1111)

    return 0
```
and call `MyMethod(-2)`, it matches the OTHER case and returns the tmp var (3) as it should.
Remove the `return 0` from the end of the method and again the behavior of returning 0 can be duplicated.

_(side note: after you'd suggested adding the return 0 to the end of the method, I tried playing with a few things, and before the return 0, I added an empty endless repeat loop - this seemed to hang the compiler with ~100% usage of one PC core)_

**Comment by totalspectrum** [comment]
Thank you. I think I found the root cause of what you saw -- the Spin function analysis code was not correctly noticing the return statement inside the case, and thought that the function did not return any value at all. This should be fixed in the current github, as should the infinite loop you saw in the compiler.

**Comment by avsa242** [comment]
Confirmed fixed, on both counts - thanks!
