### ISSUE TITLE
Underscore-only CONstants cause syntax error

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#54]
```spin
CON

_  = 1
__ = 2

PUB no
repeat
```
This works in every other Spin compiler, so I guess it's legit.
(If you want a real-world file using this, look at [any Retronitus (DX) song file](https://gitlab.com/irqsome/retronitus-dx/-/tree/master/songs)) (none of which compile anyways due to #48)

**Comment by totalspectrum** [comment]
This is due to _ having a special use in Spin2 to mark unused variables in multiple assignments. I'm moving that usage to be kept only in .spin2 files so as to keep compatibility with plain .spin.

I'll also fix #48.

Thanks for the bug report!
