### ISSUE TITLE
_FREE / _STACK don't work

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#55]
Seems like a really trivial feature...
This should not compile:
```spin
CON
_FREE = 7000
PUB NO
	OUTA := mygunk[INA]
DAT
mygunk
long 0[2000]
```
(`OUTA := mygunk[INA]` added to work around optimization)

**Comment by Wuerfel21** [comment]
Any progress on this essential feature? Having to debug weird issues caused by running out of stack with no warning at all is not very nice.

**Comment by totalspectrum** [comment]
These are implemented in github now. The error message is a warning rather than an error, just in case people are doing weird things like using fastspin to build binaries that aren't intended for loading.

**Comment by Wuerfel21** [comment]
Uhm, small problem: _STACK and _FREE are both supposed to be in units of longs, while you treat them as bytes.

**Comment by totalspectrum** [comment]
Aargh, should have checked that before I commited. Thanks for catching it, it's fixed now.

**Comment by Wuerfel21** [comment]
Can you add a flag to turn this into a proper error? (so that build scripts can halt when it happens)

**Comment by totalspectrum** [comment]
I've added a -Werror flag to turn warnings into errors.
