### ISSUE TITLE
FlexC ignores local var re-declaration

### ISSUE THREAD

**Issue by reltham** [totalspectrum/spin2cpp#56]
This code compiles without error:
```C
#include "simpletools.h"

int  main()
{
  int f = 2;
  for (int i = 0; i < 10; i++)
  {
	print("f = %d\n", f);
	f += 1;
  }
  int f = 20;
  for (int i = 0; i < 9; i++)
  {
	print("f = %d\n", f);
	f += 10;
  }
  int f = 200;
  for (int i = 0; i < 9; i++)
  {
	print("f = %d\n", f);
	f += 100;
  }
}
```
I would have expected an error on the "int f = 20;" line and the "int f = 200;" line.
The above code outputs this:
```
f = 2
f = 3
f = 4
f = 5
f = 6
f = 7
f = 8
f = 9
f = 10
f = 11
f = 12
f = 22
f = 32
f = 42
f = 52
f = 62
f = 72
f = 82
f = 92
f = 102
f = 202
f = 302
f = 402
f = 502
f = 602
f = 702
f = 802
f = 902
```
So you can see it's just completely ignoring those lines with the re-declarations with assignments.
It works correctly if I fix the code to be proper, of course.

**Comment by totalspectrum** [comment]
There's a warning now for redefined variables.

**Comment by reltham** [comment]
Shouldn't it be an error?
If not then, shouldn't the assignment happen in the redefinition? The assignment is not happening for the int f = 20; and int f = 200; lines in the above example.
