### ISSUE TITLE
Enhancement request: spin2cpp flag '-f' list #included files as well?

### ISSUE THREAD

**Issue by avsa242** [totalspectrum/spin2cpp#57]
@totalspectrum 
I noticed this handy flag today:
`  [ -f ]             output list of file names`

Would it be practical to add support for adding files to that list that are included by the preprocessor (or is there a way to switch that on, currently?). This flag is handy for writing a script to package up everything into an archive, but it misses #included files. Low-priority request as it isn't something I use very often.

Thanks!

**Comment by electrodude** [comment]
While you're at it, could you add something along the lines of GCC's `-M` flag for auto-generating Makefile dependencies?

**Comment by totalspectrum** [comment]
This will be fairly complicated (the preprocessor is separate from the main compiler, and there are two different preprocessors used by different languages). So it's going to have to wait.

**Comment by Wuerfel21** [comment]
+1 for GCC-style `-MMD` flag

**Comment by totalspectrum** [comment]
-f does print included files now (except for standard system files included in C with a <foo> style syntax).

**Comment by totalspectrum** [comment]
And I've added -MMD to flexcc.
