### ISSUE TITLE
Bitfield assignments to variables always cause segfault with `error: internal error in range assign`

### ISSUE THREAD

**Issue by electrodude** [totalspectrum/spin2cpp#58]
Bitfield assignments to variables cause `fastspin -2` to segfault with the following error:
```
<file>.spin2:<lineno>: error: internal error in range assign
```

Some reduced examples which fail:
```spin
PUB f | x
 x.[0] := 0
```
```spin
PUB f | x
  x.[1..0] := 0
```
```spin
PUB f | x
  x.[0 addbits 1] := 0
```
```spin
VAR
  long x
PUB f
  x.[0] := 0
```
```spin
PUB f
  x.[0] := 0
DAT
x       long 0
```
It even happens if I never define `x`:
```spin
PUB f
  x.[0] := 0
```

On the other hand, similar code to read a bitfield works as expected:
It even fails with the same error if I never define `x`:
```spin
PUB f(x)
  return x.[0]
```
yields:
```spin
dat
...
_f
'   return x.[0]
	and	arg01, #1
	mov	result1, arg01
_f_ret
	reta
```

**Comment by totalspectrum** [comment]
Thanks for the bug report! This problem should be fixed now.
