### ISSUE TITLE
Internal error on cases with a negative constant

### ISSUE THREAD

**Issue by avsa242** [totalspectrum/spin2cpp#59]
Hi Eric,

I just ran across an internal error (error: Internal Error: emitting move to immediate, one for each occurrence) that's triggered when a specific case has negative numbers
I was able to distill it down to this snippet:

```
PUB TXPower(dBm=-2) | tmp
' Set transmit mode RF output power, in dBm
'   Valid values: -18, -12, -6, 0
'   Any other value polls the chip and returns the current setting
'    readReg (core#NRF24_RF_SETUP, 1, @tmp)
    case dBm
        -18, -12, -6, 0:    ' Fail
'        18, 12, 6, 0:       ' OK
'            dBm := lookdownz(dBm: -18, -12, -6, 0)
'            dBm := dBm << core#FLD_RF_PWR
'        OTHER:
'            tmp := (tmp >> core#FLD_RF_PWR) & core#BITS_RF_PWR
'            result := lookupz(tmp: -18, -12, -6, 0)
'            return

'    tmp &= core#MASK_RF_PWR
'    tmp := (tmp | dBm) & core#NRF24_RF_SETUP_MASK
'    writeReg (core#NRF24_RF_SETUP, 1, @tmp)
```

As indicated in the comments on the case lines, changing the constants to positive numbers builds successfully.
It looks like this first started in 05aa54bb6cedcee54c60a155a4566377470c24bc

Any ideas? Thanks in advance!
Jesse

**Comment by totalspectrum** [comment]
Ouch, that's a nasty one Jesse, thanks for bringing it to my attention. I'll try to come up with a fix. For now you can work around it by definiting constants, e.g.:
CON
  m18 = -18
  m16 = -16
and so on, then using those in place of the literal values.

**Comment by avsa242** [comment]
Ahh cool, thanks...didn't think of that

Cheers

**Comment by totalspectrum** [comment]
This is fixed in github now.
