### ISSUE TITLE
spin2pasm branch won't compile on Mac OS X

### ISSUE THREAD

**Issue by dgately** [totalspectrum/spin2cpp#6]
Although the master branch of spin2cpp builds on Mac OS X, the spin2pasm branch gives the following error(s) on 'make all':

$ make all
mkdir -p ./build
bison -t -b ./build/spin -d spin.y
spin.y:204.1-11: error: invalid directive: ‘%precedence’
spin.y:205.1-11: error: invalid directive: ‘%precedence’
make: *** [build/spin.tab.h] Error 1

**Comment by totalspectrum** [comment]
It sounds like you may have an older version of bison. It's OK though, I think using %right instead of %precedence should work fine, so I've checked in that change. It should compile for you now. Thanks for the bug report.
