### ISSUE TITLE
Question Regarding Compiling Code in Microsoft Visual Studio 2013! .exe

### ISSUE THREAD

**Issue by charleswri631** [totalspectrum/spin2cpp#60]
Question Regarding Compiling Code in Microsoft Visual Studio 2013!

My problem is that I am unsure how to set up Microsoft Visual Studio 2013 so that It will compile without any errors or warnings. I assume that I will need to select all Include directories and add these directories to the Include locations settings parameter. I am unsure of this activity as to which directories to include as include directories and If there is anything else that needs to be completed before an attempt to compile is committed.

I assume all of the code is correctly written and that there should be no errors at attempting to compile the code.

I downloaded the entire folder as it is given and open as a project which selects all the files and adds these files into the project as a solution project in Microsoft Visual Studio 2013.

What do you use to compile this project? Is it Microsoft Visual Studio! And if it is which settings do you set to complete all requirements before compile time.

Also is there any way to get a compiled version of this project already fully functional not just the source code which is also a great advantage to fully understand the project construction as to how the .exe file does its job.

If so where could I find a fully functional already compiled version of spin2cpp so that I can test it to see how it works. 

If so I recommend adding the fully functional version also to this site that way there is access to the source and the program.

**Comment by totalspectrum** [comment]
I have never tried to build spin2cpp or fastspin with Microsoft Visual Studio. I've used mingw32 (on WIndows), gcc (on Linux), and clang (on Mac), all of them built with a Makefile.

Prebuilt versions of spin2cpp and fastspin are available from the "Releases" tab (https://github.com/totalspectrum/spin2cpp/releases). There's also a more user-friendly GUI available from https://github.com/totalspectrum/flexgui/releases, which you may find easier to use for Propeller1 and Propeller2 programming.
