### ISSUE TITLE
Question regarding option in spin2cpp.exe -ccode:

### ISSUE THREAD

**Issue by charleswri631** [totalspectrum/spin2cpp#61]
--ccode Output C code instead of C++. Note that in C mode methods typically have a first parameter "self" which points to the object's data. This is similar to the way the C++ compiler implements object methods internally, but in C it has to be exposed explicitly.

What does this ask when referring to the first parameter?
Do you have an example for me?

_### **Note that in C mode methods typically have a first parameter "self" which points to the object's data. This is similar to the way the C++ compiler implements object methods internally, but in C it has to be exposed explicitly.**_

**Comment by totalspectrum** [comment]
What it means is that the translated C code (the output from spin2cpp) has an extra parameter which points to the method data (the variables in the Spin VAR section). This is added automatically by spin2cpp. It's only of concern if you want to call the translated Spin function from your own C code.

**Comment by charleswri631** [comment]
do I give it the name of the function I will use if I call it from c and is it the first function call in the spin file "spin function call MAIN", What if there is more public function that will be called from the spin file or if it has an OBJ specified in the spin file?

**Comment by totalspectrum** [comment]
The entire .spin file is turned into a C structure (or C++ class), declared in a .h file. Both the struct and the .h get names based on the Spin file name, In order to use the Spin object from C you would #include the .h file and declare a structure of the appropriate type. So to call method bar(x,y) from foo.spin you would do something like
#include "foo.h"
struct foo A;
...
   foo_bar(&A, x, y)
...

It's easiest to see if you actually convert some sample .spin file and look at the generated .c and .h files. 

If you have access to a C++ compiler that makes things a bit easier, since then you can just do something like:

class foo A;
...
A.bar(x, y);

**Comment by charleswri631** [comment]
Does it create a c file? foo.c and foo.h

**Comment by charleswri631** [comment]
is that somehow related to the parameter?
What does this ask when referring to the first parameter?
Do you have an example for me?
Before I type spin2cpp.exe "self" ccode    ---? what should be typed in cmd command prompt example.

**Comment by totalspectrum** [comment]
To convert a file foo.spin into foo.c and foo.h, do:

    spin2cpp --ccode foo.spin

Let's back up here... what exactly do you wish to accomplish? Do you have a specific Spin file that you wish to convert to C? What C compiler are you using for the Propeller?

**Comment by charleswri631** [comment]
VGA.spin This file is given with Propeller Spin Tool which lets you write SPIN and PASM code and upload it onto the propeller chip. I am using Propeller GCC Simple IDE to write C code and upload it onto the propeller.

**Comment by charleswri631** [comment]
what about the first parameter which it asks me to supply?

What does this ask when referring to the first parameter?
Do you have an example for me?

### Note that in C mode methods typically have a first parameter "self" which points to the object's data. This is similar to the way the C++ compiler implements object methods internally, but in C it has to be exposed explicitly.

**Comment by charleswri631** [comment]
spin2cpp --ccode foo.spin 

I don't see the first parameter?

**Comment by charleswri631** [comment]
So It does work I end up with those two files VGA.c & VGA.h  
Now it's just regarding the first parameter!
It looks like I don't need it. For VGA.spin file
So it does work if I have any other problems I will ask questions again
Thank You for such help! 
Really appreciate the help!

**Comment by charleswri631** [comment]
Finished with this Question!
