### ISSUE TITLE
FTBFS (spin2): Case with negative numbers in range to 0

### ISSUE THREAD

**Issue by avsa242** [totalspectrum/spin2cpp#62]
Hi Eric,
I just updated to head after being on something from May and found that certain case statements fail to build, with the error:
`error: Duplicate case value` (no source filename or line number given)
It seems that using certain negative numbers in a range, or as discrete values are being considered duplicate cases.

I've been able to reproduce it with the following code:
```
PUB CaseDupeError(param): result | tmp

    tmp := $00
    case param
        -3..0:                      ' Fails
            ' Original case that produced the error
        OTHER:

```

Other tests:

Fails:
```
        -3:
        -2:
        -1:
        0:
```

Accepted:
```
        -1:
        0:
```

Accepted:
```
        0:
```

Accepted:
```
        -3..-1:
```

Accepted:
```
        3..0:
```

Traced this back to: 40b9cbc4b6c52775ee4a11ed7b365609398ade8e

**Comment by totalspectrum** [comment]
Thanks for the bug report! This should be fixed now in the latest sources (4.2.3-beta).
