### ISSUE TITLE
Assignment form of some operators not accepted

### ISSUE THREAD

**Issue by avsa242** [totalspectrum/spin2cpp#63]
Hi Eric,

You may simply have just not implemented these or some of these yet (or intend for the syntax to be slightly different), but in converting some of my older spin2 sources to current FastSpin/closer-to-PNut syntax, I first came across ```result SIGNX= 15 ``` not being accepted (```result SIGNX 15``` is ok). I _think_ I'm using it correctly, going by the official spin2 docs.
I also tested some of the other operators to see if any others were affected:

Accepted:
sar=, ror=, rol=, scas=, ^^=, ||=

Fails: 
```error: syntax error, unexpected '='```
rev=, zerox=, signx=, sca=, addbits=, addpins=, &&=

Fails, with slightly different error:
```error: syntax error, unexpected ___```
 (repl ___ with operator below)

sqrt=, ones=, bmask=, decod=, encod=, !=, !!=

Code to reproduce:
```
PUB method | val

    val rev= 15  ' or other operator

'    sqrt= var     ' for other operators
```

Thanks!
Jesse

**Comment by totalspectrum** [comment]
Thank you for the bug report, Jesse!

I hadn't gotten around to implementing many of the Spin2 operators, but it clearly was time to do so. I think they should all be there now in github.
