### ISSUE TITLE
Enhancement request: Optional warning or error on official SPIN2 lexicon errors

### ISSUE THREAD

**Issue by avsa242** [totalspectrum/spin2cpp#64]
Hi Eric,

Would it be practical to have FastSpin _optionally_ (e.g., something like gcc's -Werror, or other -W series of flags) emit a warning or even error out on syntax that isn't compliant with the official SPIN2 definitions? For example, things like the () at the end of a method definition or reference aren't strictly required in FastSpin, but _are_ in PNut/PropTool. In the interest of making it easier to maintain code that's as compatible with PNut as possible while still using FastSpin, having the compiler generate warnings or errors would be helpful, as I find it difficult to consistently remember what's required by PNut, and can't catch all occurrences with regex.

Thanks for your consideration either way!

**Comment by totalspectrum** [comment]
Thanks Jesse. That does sound like a useful feature. I've added a "-Wall" option to the github source to enable all warnings (eventually I hope to provide finer grained control over the warnings). It won't catch all the differences, but it should warn about some of them (like the method definition/reference one you mentioned). Could you give it a try?

**Comment by avsa242** [comment]
It already caught some I missed:
``
/home/avsa242/prop/github/p2-spin-standard-library/library/lib.ansiterminal.spin2:285: warning: omitting () for empty parameter lists is a fastspin extension
``

And it caught a few others, notably asm..endasm

Perfect start...thanks!

**Comment by totalspectrum** [comment]
Closing this as the basic warnings are present now. There is always room for improvement of course.
