### ISSUE TITLE
Weird Spin bug

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#65]
Sorry for the nondescript title, but I really have no idea what the bug is.

I think the code speaks for itself.  The sin function works in PropTool, but returns weird shit in fastspin.
 
[fastspin_bug - Archive  [Date 2020.07.13  Time 22.19].zip](https://github.com/totalspectrum/spin2cpp/files/4914879/fastspin_bug.-.Archive.Date.2020.07.13.Time.22.19.zip)

**Comment by Wuerfel21** [comment]
looking at the code being emitted:

```
_sin
	test	arg01, imm_2048_ wz
	test	arg01, imm_4096_ wz
 if_ne	neg	arg01, arg01
	or	arg01, imm_28672_
	shl	arg01, #1
	rdword	_var01, arg01
 if_ne	neg	_var01, _var01
	mov	result1, _var01
_sin_ret
	call	#LMM_RET
```
yeah that's a yikes

**Comment by totalspectrum** [comment]
Thanks for the bug report! yes, the optimizer missed noticing the "if_ne" between the AND and it's use. It's fixed in github now. Are you able to build from source?

**Comment by Wuerfel21** [comment]
I probably could build from source, but I've found a workaround for that particular function, so I can wait for the next release just fine.

**Comment by totalspectrum** [comment]
OK, thanks. There'll be a new binary release soon.
