### ISSUE TITLE
Fastspin allocates too many registers

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#68]
... leading to `error: fit 496 failed: pc is (something big)`
diffing the pasm file between reveals that for a program I'm working on, not only does the number of localXX registers more than double, but also that for some reason 9 whole registers get wasted on PST intialization:
```
Parallax_serial_terminal_Stop_tmp001_
	res	1
Parallax_serial_terminal_Stop_tmp002_
	res	1
_Parallax_serial_terminal_StartRxTx__cse__0169
	res	1
_Parallax_serial_terminal_StartRxTx__cse__0170
	res	1
_Parallax_serial_terminal_StartRxTx_baudrate
	res	1
_Parallax_serial_terminal_StartRxTx_mode
	res	1
_Parallax_serial_terminal_StartRxTx_rxpin
	res	1
_Parallax_serial_terminal_StartRxTx_txpin
	res	1
_Parallax_serial_terminal_Start_okay
	res	1
```

**Comment by Wuerfel21** [comment]
Relatedly: After making the program even bigger, O2 gets me an `error: Internal error exceeded local register limit`

**Comment by totalspectrum** [comment]
This is probably a little bit better now, but it will never be as good as -O1, which is one reason that -O1 and -O2 exist as separate choices (you can trade off memory usage, including COG memory, vs. performance).

**Comment by Wuerfel21** [comment]
Could you add more precise control over which optimizations are performed (and how aggressively, where applicable) and make O1/O2 presets, like in GCC?

**Comment by Wuerfel21** [comment]
Oh, no it is haunting me again, but now on O1, too. (O0 compiles some 40K binary so that's a nope, too)
```
hexagon.pasm:5285: error: fit 496 failed: pc is 497
```
However, as kindof mentioned above, fastspin seems to like wasting registers by allocating them to variables of the main function, so I was able to free a couple up by making the main function as simple as possible, which was enough to get me going again for now.

**Comment by totalspectrum** [comment]
Yes, the top level function was getting its own registers and there was no need for that. That's fixed now, and I've also put in a namespace change which I hope will allow some register re-use at optimization level -O2.

**Comment by Wuerfel21** [comment]
doesn't seem to make any difference on my code at -O2

**Comment by totalspectrum** [comment]
I have added more precise control over optimizations, including on a per-function basis.

**Comment by Wuerfel21** [comment]
Thanks, will have to try it some time

**Comment by Wuerfel21** [comment]
Good: Wow, O2 minus CSE is pretty good

Bad: per-function doesn't actually work. adding `{++opt(cse)}` to a function nets me a `error: Unrecognized optimization flag: (cse)`

**Comment by totalspectrum** [comment]
I see {++opt(cse)} is better now, and overall flexspin is allocating fewer registers than it used to. It's still more than ideal, but going lower with register usage is a major overall. I'm going to close this particular bug for now.
