### ISSUE TITLE
Dead code elimination does not work on Spin CASE statements

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#69]

**Comment by totalspectrum** [comment]
Some dead code elimination works in CASE statements, some does not. Could you give an example of something you were hoping would work?

**Comment by Wuerfel21** [comment]
I didn't provide a description because even a dead-simple CASE won't get eliminated (tried on git commit a2a2ad607934ec7b9d95dc6502586f6f50f42ef4 ):

```
CON

_clkmode = xtal1 + pll16x
_xinfreq = 5_000_000

OBJ

pst: "Parallax Serial Terminal"
PUB main
  pst.start(115_200)

  repeat
    case 2
      1: pst.char("a")
      2: pst.char("b")
      3: pst.char("c")
```

**Comment by totalspectrum** [comment]
Ah, I misunderstood your original comment: I thought you were talking about the expressions and statements inside the case, rather than the situation where the case expression itself is constant. Thanks, I'll look into that.

**Comment by totalspectrum** [comment]
This should work now, at least for simple cases like the one you showed. Thanks!
