### ISSUE TITLE
Add warning when using uninitialized (non-RESULT) local variables

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#70]
Not sure how difficult it'd be, but could a warning for code like this be added?
```
VAR

long arr[199]
    
PUB test | i

arr[i] := 2

```

**Comment by totalspectrum** [comment]
That's a good idea, but I'm not sure how it could be done. I'll leave this open for now.

**Comment by totalspectrum** [comment]
Now implemented, although (for now) it's only enabled by -Wall -- I'm not sure how reliable it is so I want it to be easy to turn off.
