### ISSUE TITLE
Something to note perhaps: Spin@@ operator truncates to 16 bit in bytecode spin

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#71]
As it says: In bytecode spin1, the result of the @@ operator is truncated to 16 bits, in fastspin it isn't.

I don't think it's a good idea to change this, as I assume that'd increase code size. I think this difference should just be documented

**Comment by totalspectrum** [comment]
Addresses always fit in 16 bits, so how could we tell the difference? I must be missing something.

**Comment by Wuerfel21** [comment]
Assume you have some long that is an object-relative pointer plus some metadata packed into the unused top half:
```
long @pattern_multic    +PATTERN_CW  + OFFSET_RANDOMIZE2<<PATTERN_OFFSET_SHIFT  + 2<<PATTERN_WEIGHT_SHIFT
```
In bytecode spin the top bits will get masked off when @@-ing such a long (A workaround is to do `@@0 + mylong` instead of `@@mylong`

**Comment by Wuerfel21** [comment]
A test program showing the difference:
```
CON

_clkmode = xtal1 + pll16x
_xinfreq = 5_000_000

OBJ

pst: "Parallax Serial Terminal"
PUB main
  pst.start(115_200)

  repeat 
    pst.hex(@@$10000 - @@0,8)
    pst.newline
```
PropTool prints 00000000, fastspin prints 00010000

**Comment by Wuerfel21** [comment]
Also found the relevant instruction in the interpreter: https://github.com/parallaxinc/Propeller_1_Design/blob/master/interpreter.src#L841

No idea why it does this though.

**Comment by totalspectrum** [comment]
Thanks. I've added a not about this in doc/spin.md.
