### ISSUE TITLE
Variables can be used without declaring them, but only sometimes

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#73]
Is this a buggy, undocumented intended feature or a just a bug?
It seems to depend on the name, but I can't really find any pattern - "tmp" seems to always be like this though.
I use "tmp" variables all the time and haven't noticed anything going wrong, so this bug doesn't seem to affect correct programs.

```spin
'' This compiles fine
CON
_clkmode = xtal1 + pll16x
_xinfreq = 5_000_000
OBJ
pst: "Parallax Serial Terminal"
PUB main
  pst.start(115_200)
  repeat 
    tmp := 123
    pst.dec(tmp)    
    pst.newline
```

```spin
'' This does not compile
CON
_clkmode = xtal1 + pll16x
_xinfreq = 5_000_000
OBJ
pst: "Parallax Serial Terminal"
PUB main
  pst.start(115_200)
  repeat 
    abc := 123
    pst.dec(abc)    
    pst.newline
```

**Comment by totalspectrum** [comment]
Thanks for the bug report. One of the system functions was declaring a global called "tmp". I've renamed that now.
