### ISSUE TITLE
Incorrect DAT operator precedence between @ and [x]

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#74]
```
DAT
word @something[2]
```
is handled incorrectly: fastspin emits one word that is `@something +2` instead of two words of `@something`

...
I just keep finding these, do I?
...

**Comment by totalspectrum** [comment]
You have a good eye for bugs, and thanks for reporting them!

This one is particularly nasty because it seems @something[2] means different things in different contexts :(. I'll have to think about how to work around this.

**Comment by Wuerfel21** [comment]
Relatedly, lines like
```spin
long ((0*64)+(1*64)<<16)+2[16*14 - 4] 
```
do not parse correctly, either. But at least that causes an error.

**Comment by totalspectrum** [comment]
I think I've managed to figure out a way to fix this, and it's checked in now.
