### ISSUE TITLE
sub-optimal REPEAT FROM TO codegen

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#75]
The most common kind is fine:
```spin
repeat i from $1000 to $2000 '' I generate good code
  word[i]:=0
```
But adding a STEP adds 5 instructions worth of unnecessary edge case handling, even though all the parameters are constants and `i` is not written inside the loop
```spin
repeat i from $1000 to $2000 step 2 '' oh no what if we ever have an odd i?
  word[i]:=0
```
Relatedly, if the FROM and TO are DAT addresses, 5 instructions worth of code and a couple variables are used to decide in which direction to step.
```spin
repeat i from @something1 to @something2 '' In space, there is no up or down...
  word[i]:=0
```

And of course, don't cross the streams
```spin
repeat i from @something1 to @something2 step 2'' One ticket straight to bloat city, please
  word[i]:=0
```

**Comment by totalspectrum** [comment]
Thanks for reporting this. It's going to take a little while to fix, unfortunately.

**Comment by totalspectrum** [comment]
This should be better than it was now. Still not perfect, but in general optimization is hampered because we don't know the final values of things like @something until after optimization is finished.
