### ISSUE TITLE
Inappropriate generation of jump table for range CASE

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#79]
```spin
CON
_clkmode = xtal1 + pll16x
_xinfreq = 5_000_000
OBJ
pst: "Parallax Serial Terminal"  
PUB main | r
  pst.start(115_200)
  repeat
    pst.str(getstr(r?//60))
PRI getstr(time) : tmp
case time
  00..09: tmp:= string("POINT")
  10..19: tmp:= string("LINE")
  20..29: tmp:= string("TRIANGLE")
  30..44: tmp:= string("SQUARE")
  45..59: tmp:= string("PENTAGON")
  other:  tmp:= string("HEXAGON")
```
The CASE here gets compiled into an enormous 61-entry jump table:
```spin
_getstr
	mov	_var01, arg01
	mov	_var02, #0
	mov	_var03, _var01
	max	_var03, #60
	mov	_var04, _var03
	shl	_var04, #3
	add	_var04, ptr_L__0029_
	mov	LMM_NEW_PC, _var04
	call	#LMM_JUMP_PTR
LR__0002
	rdlong	pc,pc
	long	@@@LR__0003
	rdlong	pc,pc
	long	@@@LR__0003
'' imagine 59 more of these
```

- I think the heuristic for deciding if a CASE should be a jump table might need tweaking....

- Why is each entry 8 bytes like that? Why isn't it like this:
```spin
_getstr
	mov	_var01, arg01
	mov	_var02, #0
	mov	_var03, _var01
	max	_var03, #60
	mov	_var04, _var03
	shl	_var04, #1
        add	_var04, ptr_L__0029_
	rdword pc,_var04
LR__0002
	word @@@LR__0003
	word @@@LR__0003
'' imagine 59 more of these and one word of padding
```

**Comment by totalspectrum** [comment]
The entries are 8 bytes because it is, literally, a jump table. And it's a jump table because we can easily generate code for that that works in COG and HUB for both P1 and P2, and the P2 version gets optimized nicely with jmprel. I'll leave this open though because it would be nice to do something different for the P1 HUB case.

**Comment by totalspectrum** [comment]
We weren't looking at how many distinct labels there were for the jump table selection decision. That's fixed now.

**Comment by totalspectrum** [comment]
I've also switched to using words for the jump table entries on P1. This should save quite a bit of space.

**Comment by Wuerfel21** [comment]
Oh yeah, sweet. Will try this later tonight. Many thanks.
