### ISSUE TITLE
spinconvert should allow lib file input from other than the current source directory

### ISSUE THREAD

**Issue by dgately** [totalspectrum/spin2cpp#8]
I keep all/most of my spin library files in a single directory. spin2cpp allows the "-I" option to declare directories where those libs can be found. spinconvert should be able to assist in declaring directories for libraries and then passing those declarations on to spin2cpp.

The following code gives an error when the file "I2C_ROMEngine.spin" is not in the same directory as the current source:

    OBJ
        ROM:     "I2C_ROMEngine"

the error:

    spin2cpp --noheader -g --normalize --code=cog --data=hub -o
    /Users/altergator/PropSpinCode/clearMem.cpp
    /Users/altergator/PropSpinCode/clearMem.spin
    I2C_ROMEngine: No such file or directory
    child process exited abnormally

**Comment by totalspectrum** [comment]
There's a "Library directory" option under Options now. Thanks for suggesting this.
