### ISSUE TITLE
x.word[1] optimization regression since 4.2.5

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#81]
```spin
CON
_clkmode = xtal1 + pll16x
_xinfreq = 5_000_000
OBJ
pst:"Parallax Serial Terminal"
PUB main | i
pst.start(115_200)
repeat
  pst.dec(i.word[1])
```
4.2.5:
```
LR__0001
	mov	arg01, local01
	shr	arg01, #16
```
Current git build:
```
LR__0001
	mov	arg01, local01
	sar	arg01, #16
	and	arg01, imm_65535_
```

**Comment by totalspectrum** [comment]
Thanks, that should be better now.

**Comment by avsa242** [comment]
I think this may still be broken in some way... I updated to 1fe7799 from 069b58c and found after some head-scratching that it's fastspin (I'd modified an I2C driver this depends on last night too so thought that was it at first). The Z-axis data of my gyroscope driver snippet below always returns 2, or maybe one other value, regardless of the data read from the chip.

This is the code - hardware-specific bits commented out (call with, e.g., ```sensor.gyrodata(@x, @y, @z)```):

```
PUB GyroData(ptr_x, ptr_y, ptr_z) | tmp[2]
' Read gyroscope data
    longfill(@tmp, 0, 2)            ' Initialize tmp to 0 (no effect, present or not)
'    readReg(core.OUT_X_L, 6, @tmp)
    tmp[0] := $FF00_FFFE    ' y, x  ' Simulates the data read by the readReg() line above: -256_-2
    tmp[1] := $0000_0010    ' z     ' 0_16

    long[ptr_x] := (tmp.word[0] signx 15)
    long[ptr_y] := (tmp.word[1] signx 15)
'    long[ptr_z] := (tmp.word[2] signx 15)  ' XX Returns 2, should be $10 (16), as in tmp[1] (returns 2 for any value I've tried to assign tmp[1], so far)
    long[ptr_z] := tmp[1] signx 15          ' OK Returns $10 (16)
```

**Comment by totalspectrum** [comment]
Yes, there was a typo in the detection for the special cases of .word[0]/.word[1] which made them apply to .word[2] (which they shouldn't have). That should be fixed now, thanks.

**Comment by avsa242** [comment]
Thanks! Confirmed
New related issue though...should this work, or has there been a design change that'd make it impractical:
```
PUB DeviceID(): id
' Read device identification
'   Returns: $683D
    id := 0
    readReg(XLG, core.WHO_AM_I_XG, 1, @id.byte[1])
    readReg(MAG, core.WHO_AM_I_M, 1, @id.byte[0])
```
specifically, the reading into the address of the return var id.byte[0] or .byte[1]?

**Comment by Wuerfel21** [comment]
Does that even work in PropTool/PNut?

**Comment by avsa242** [comment]
Not sure...don't have a Windows install to test...but it worked in fastspin up until the latest commit. That's a good point though...if it doesn't, and/or if it's impractical to fix in fastspin, I'll have to change my code

**Comment by Wuerfel21** [comment]
Last I knew, PropTool kinda works under WINE, especially the uploading is flakey (so save out a .binary and load it with whatever). PNut probably works fine except for the uploader.

**Comment by Wuerfel21** [comment]
(alternatively, try openspin)

**Comment by avsa242** [comment]
Will retry those at some point...just tried my spin1 version which uses more or less the same code, and it's accepted there, too. Not sure how far openspin diverged from the original PropTool compiler, if at all.

**Comment by totalspectrum** [comment]
Added some more changes; I hope this will work again now.

**Comment by avsa242** [comment]
Confirmed...looks like all is well! Thanks!

**Comment by avsa242** [comment]
Gah, sorry...I spoke too soon.

Assignments using _some_ size overrides on a local array barfs with:
```error: Internal error, bad value  in MaskMove```
(simply referencing them, as in previous comments is still OK)

Code to reproduce:
```
VAR

    long myvar[2]

PUB method1(p1) | mylocal[2]

    mylocal.word[0] := 1        'internal error
    mylocal.word[1] := 1        'internal error
    mylocal.word[2] := 1        'OK
    mylocal.word[3] := 1        'OK

    mylocal.byte[0] := 1        'internal error
    mylocal.byte[1] := 1        'internal error
    mylocal.byte[2] := 1        'internal error
    mylocal.byte[3] := 1        'internal error
    mylocal.byte[4] := 1        'OK
    mylocal.byte[5] := 1        'OK
    mylocal.byte[6] := 1        'OK
    mylocal.byte[7] := 1        'OK

    myvar.word[0] := 1          'OK
    myvar.byte[0] := 1          'OK
    long[p1] := mylocal.word[0] 'OK
```

VARs don't seem to be affected, though.
First bad commit is d898b8ae7b9359c96fb8c1168b80c2bff9368f4b

**Comment by totalspectrum** [comment]
I think those are fixed now. I do have some misgivings about how sensible it is to use mylocal.byte[5] instead of mylocal[1].byte[1]. All of those manipulations of arrays are going to hinder performance because they force the arrays into stack instead of memory.

**Comment by avsa242** [comment]
Hmmm ok I see what you're saying...I hadn't really seen that syntax before. When I was writing code with the former usage, I was thinking only of the visual simplicity ("byte #5 of the variable"). I didn't realize it came with a penalty. If I can work the latter syntax into my code, I'll do it that way, instead. Thanks for the fix, and the tip...

**Comment by avsa242** [comment]
No further issues with this - just wanted to comment that the second assignment syntax (```mylocal[1].byte[1]```) isn't accepted by fastspin (or openspin). I tried messy looking pointer variants: ```byte[mylocal[0]][0]```, etc - no complaints by either compiler but just got all zeroes (I might be overlooking something stupid there though - maybe that _shouldn't_ work).
