### ISSUE TITLE
P1 WAITVID Spin intrinsic not available

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#83]
Error message: `unknown identifier waitvid used in function call`

TBH it is really quite pointless to have WAITVID in Spin (altough fastspin might actually be fast enough for a really basic NTSC driver, it'd still be kinda pointless - except maybe to show off fastspin itself? IDK.), but I just noticed it isn't there.

**Comment by totalspectrum** [comment]
Thanks, I've added this (although it's probably not going to be used too much :)).
