### ISSUE TITLE
Optimizer fail: SD-MMC_FATEngine returns "Not A File" error

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#87]
Title says it all - the `SD-MMC_FATEngine.spin` object, colloquially KyeFAT, doesn't work on fastspin, for it aborts with "Not a File" when opening any file (this is the error message for when you try to open a directory as a file - opening a file that doesn't exist is supposed to be "Entry Not Found"). I haven't debugged it further yet
 because this object is very large and complicated.

I've attached the particular version I have this problem with. I think this one has some additional PUBs for reading internal state that the original doesn't have, but that shouldn't matter.
[SD-MMC_FATEngine.zip](https://github.com/totalspectrum/spin2cpp/files/5013069/SD-MMC_FATEngine.zip)

**Comment by Wuerfel21** [comment]
So I debugged it some. There's only one place the Not_A_File error code is used and it looks like this
```spin
    if(isDIRDirectory)
      abortError(Not_A_File)
```
and isDIRDirectory is defined as such
```spin
PRI isDIRDirectory ' 10 Stack Longs

  result or= (readDIRAttributes & $10)
```
Now fastspin compiles this as follows:
```
'     if(isDIRDirectory)
' 
'   result or= (readDIRAttributes & $10)
	call	#LMM_CALL
	long	@@@_Sd_mmc_fatengine_readDIRAttributes
	mov	local13, #0
 if_ne	neg	local13, #1
	mov	result1, local13 wz
 if_e	add	pc, #4*(LR__0070 - ($+1))
'       abortError(Not_A_File)
	mov	arg01, #18
	call	#LMM_CALL
	long	@@@_Sd_mmc_fatengine_abortError
LR__0070
```
As far as I can tell, *a `and result1,#$10 wz` that should be after the call is being optimized out when it shouldn't be* (also the whole thing about getting true/false into result1 is kinda pointless)

**Comment by Wuerfel21** [comment]
Indeed, that instruction is there when I compile with `-O0`.
So I it really is an optimizer bug.

**Comment by totalspectrum** [comment]
Thank you. Yes, there was a typo in some optimizer code which was causing the instruction to be incorrectly flagged as dead. It should be fixed now.
