### ISSUE TITLE
spinconveri (spinpasm) should handle 'reboot' symbol as does C & C++

### ISSUE THREAD

**Issue by dgately** [totalspectrum/spin2cpp#9]
Just another unhandled-by-PASM issue... Appears that reboot is not handled only for PASM. C & C++ work!

code (from Cluso's demo code for P8XBlade2/CpuBlade7):

      if (ina[3] ==1)
        reboot

output:

spin2cpp --noheader -g --asm --code=cog --data=hub -o /Users/altergator/PropSpinCode/LEDOnOffCluso/cylonLED.pasm /Users/altergator/PropSpinCode/LEDOnOffCluso/cylonLED.spin
/Users/altergator/PropSpinCode/LEDOnOffCluso/cylonLED.spin:32: error: Symbol reboot is of a type not handled by PASM output yet
child process exited abnormally

**Comment by totalspectrum** [comment]
Thanks for the bug report. This is fixed in the current master now.
