### ISSUE TITLE
-O2 completly broken on current git build

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#92]
Compiling my project on O2 on 4.2.8 (fcache must be disabled to make it fit) produces a (slightly buggy) binary of 28572 bytes (vs 28568 bytes in my previous build (`4.2.8-beta-v4.2.7-2-g3d8a1e06`), oddly enough. I think that's due to the ORG alignment thing).
Compiling my project on O2 with a current git build gives a binary of 45012 bytes (obviously can't load that one to see if it works). O1 is still fine.

**Comment by Wuerfel21** [comment]
Ahh, I figured it out: It doesn't actually enable all the O1 optimizations anymore when you select O2

**Comment by totalspectrum** [comment]
-O1 should be a subset of -O2. Is it still happening with the latest build? Which project were you testing with?

**Comment by Wuerfel21** [comment]
Project is the now released [Spin Hexagon](https://github.com/IRQsome/Spin-Hexagon) (given how many bugs I found writing this, the code might be worth a read...). The particular build was/is `4.3.0-beta-v4.2.7-25-gbe7dc48a`. Haven't tested the very latest yet.

**Comment by Wuerfel21** [comment]
Yup, problem persists on lastest commit (0335dda6b5ed73b93f848d17776b54f95bdf80d5)

**Comment by totalspectrum** [comment]
Oh, duh: -O2 was only enabling the difference between what -O2 should have been and what -O1 is. I didn't notice it because just plain -O (which is supposed to be a synonym for -O2) actually *was* working correctly :(. Fixed now, thanks.
