### ISSUE TITLE
flexspin fails to build lookup/lookdown code that uses a range

### ISSUE THREAD

**Issue by avsa242** [totalspectrum/spin2cpp#98]
Reference the following test code:
```
CON

    CON_SYM = 100000
'    CON_SYM = 1000000    ' flexspin exits with command terminated
'    CON_SYM = 10000000   ' same, but takes longer, consumes more memory

PUB main()

    lookdown_literal_test(1)
'    lookdown_CON_test(1)


PUB lookdown_literal_test(param1)

    if lookdown(param1: 1..100000)  ' produced code size grows proportionally
        return true                 '   to the "upper" range

PUB lookdown_CON_test(param1)

    if lookdown(param1: 1..CON_SYM) ' symbolic constant behaves the same way
        return true
```
If the value of CON_SYM (or 100000 in ```lookdown_literal_test()```) is small enough to complete the build, flexspin reports produced code size that grows in proportion to the upper or maximum side of the range specified in a lookdown/lookup statement (includes zero-based variants). If the max is large enough, flexspin exits with 'command terminated', or appears to hang (pegs one core with memory usage steadily climbing). Using a literal number or a symbolic CONstant exhibits the same behavior.

This is using the v5.0.0 tag on Linux. I went as far back as v4.0.something from late last year with the same results.

Cheers!
Jesse

**Comment by totalspectrum** [comment]
A fix for this is checked in to github now.
