### ISSUE TITLE
Minor register allocation bug introduced between 4.3.0 and 5.0.0

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#99]
After fixing the Rakefile for [Spin Hexagon](https://github.com/IRQsome/Spin-Hexagon) to handle the fastspin/flexspin command renaming nonsense, out of curiosity, I diffed the PASM listings from 4.3.0 and 5.0.0.

Oddly enough, 5.0.0 allocates a lone `_time2dualstr_frames` register that never gets used. (The functionality of the time2dualstr function seems unimpacted)

[Here's the two listings...](https://github.com/totalspectrum/spin2cpp/files/5470965/listings.zip)

**Comment by totalspectrum** [comment]
A whole lot has changed since 5.0.0, and I think this bug is probably fixed now... if not, we should re-open with a new test case.
